CREATE TABLE `rt_current_engine_locks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lock_name` varchar(64) NOT NULL,
	`owner_token` varchar(64),
	`lease_until` timestamp,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rt_current_engine_locks_id` PRIMARY KEY(`id`),
	CONSTRAINT `rt_current_engine_lock_identity` UNIQUE(`lock_name`)
);
--> statement-breakpoint
CREATE TABLE `rt_divergence_hypotheses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analysis_version` varchar(64) NOT NULL,
	`as_of_date` varchar(10) NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`route_id` varchar(96) NOT NULL,
	`cause_code` varchar(64) NOT NULL,
	`rt_divergence_confidence` enum('low','medium','high') NOT NULL,
	`realtime_loss_count` int NOT NULL DEFAULT 0,
	`historical_loss_hit` int NOT NULL DEFAULT 0,
	`historical_win_hit` int NOT NULL DEFAULT 0,
	`prevented_loss_yen` bigint NOT NULL DEFAULT 0,
	`lost_win_yen` bigint NOT NULL DEFAULT 0,
	`following_trade_delta_yen` bigint NOT NULL DEFAULT 0,
	`portfolio_delta_yen` bigint NOT NULL DEFAULT 0,
	`rt_divergence_status` enum('observing','shadow_candidate','rejected') NOT NULL DEFAULT 'observing',
	`metrics_json` json NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rt_divergence_hypotheses_id` PRIMARY KEY(`id`),
	CONSTRAINT `rt_divergence_hypothesis_identity` UNIQUE(`analysis_version`,`as_of_date`,`symbol`,`route_id`,`cause_code`)
);
--> statement-breakpoint
CREATE TABLE `rt_outcome_labels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`baseline_version` varchar(64) NOT NULL,
	`entry_source_event_id` varchar(128) NOT NULL,
	`exit_source_event_id` varchar(128),
	`trade_date` varchar(10) NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`route_id` varchar(96) NOT NULL,
	`rt_outcome_label_side` enum('long','short') NOT NULL,
	`entry_price` decimal(12,4) NOT NULL,
	`exit_price` decimal(12,4),
	`shares` int NOT NULL,
	`mfe_pct` decimal(10,6),
	`mae_pct` decimal(10,6),
	`after_1m_pct` decimal(10,6),
	`after_3m_pct` decimal(10,6),
	`after_5m_pct` decimal(10,6),
	`final_pnl` bigint,
	`counterfactual_json` json,
	`diagnosis_only` boolean NOT NULL DEFAULT true,
	`completed` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rt_outcome_labels_id` PRIMARY KEY(`id`),
	CONSTRAINT `rt_outcome_label_identity` UNIQUE(`baseline_version`,`entry_source_event_id`)
);
--> statement-breakpoint
CREATE TABLE `rt_portfolio_audit_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`portfolio_version` varchar(64) NOT NULL,
	`rt_portfolio_audit_mode` enum('actual_receipt','minute_normalized') NOT NULL,
	`source_event_id` varchar(128) NOT NULL,
	`trade_date` varchar(10) NOT NULL,
	`candle_time` varchar(5) NOT NULL,
	`batch_key` varchar(32) NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`route_id` varchar(96),
	`rt_portfolio_audit_side` enum('long','short'),
	`priority_rank` int,
	`rt_portfolio_audit_decision` enum('accepted','margin_block','not_candidate','missing','closed') NOT NULL,
	`shares` int,
	`required_margin` bigint,
	`margin_used_before` bigint NOT NULL DEFAULT 0,
	`margin_used_after` bigint NOT NULL DEFAULT 0,
	`blocker_source_event_id` varchar(128),
	`blocker_symbol` varchar(10),
	`detail_json` json NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rt_portfolio_audit_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `rt_portfolio_audit_identity` UNIQUE(`portfolio_version`,`rt_portfolio_audit_mode`,`source_event_id`)
);
--> statement-breakpoint
CREATE TABLE `rt_realtime_decision_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source_event_db_id` int NOT NULL,
	`source_event_id` varchar(128) NOT NULL,
	`relay_session_id` varchar(96) NOT NULL,
	`event_seq` int NOT NULL,
	`trade_date` varchar(10) NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`candle_time` varchar(5) NOT NULL,
	`decision_started_at_ms` bigint NOT NULL,
	`decision_completed_at_ms` bigint NOT NULL,
	`rt_realtime_decision_result` enum('no_signal','pending','rejected','entry','hold','exit','error') NOT NULL,
	`route_id` varchar(96),
	`rt_realtime_decision_side` enum('long','short'),
	`reason` text,
	`input_hash` varchar(64) NOT NULL,
	`state_before_json` json NOT NULL,
	`state_after_json` json NOT NULL,
	`state_hash_before` varchar(64) NOT NULL,
	`state_hash_after` varchar(64) NOT NULL,
	`signal_reference_price` decimal(12,4),
	`market_observed_price` decimal(12,4),
	`board_price_time` varchar(40),
	`executable_price_proxy` decimal(12,4),
	`simulated_bar_fill_price` decimal(12,4),
	`broker_execution_price` decimal(12,4),
	`shares` int,
	`amount` bigint,
	`margin_used_before` bigint,
	`margin_used_after` bigint,
	`rt_realtime_causality_status` enum('pass','violation','unverified','not_applicable') NOT NULL DEFAULT 'unverified',
	`causality_reason` text,
	`result_json` json NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rt_realtime_decision_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `rt_realtime_decision_source_identity` UNIQUE(`source_event_id`)
);
--> statement-breakpoint
CREATE TABLE `rt_replay_comparisons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`baseline_version` varchar(64) NOT NULL,
	`source_event_db_id` int NOT NULL,
	`source_event_id` varchar(128) NOT NULL,
	`engine_sequence` int,
	`trade_date` varchar(10) NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`candle_time` varchar(5) NOT NULL,
	`rt_replay_match_status` enum('match','mismatch','skipped','error') NOT NULL,
	`is_first_mismatch` boolean NOT NULL DEFAULT false,
	`mismatch_type` varchar(64),
	`realtime_decision_id` int,
	`realtime_state_hash` varchar(64),
	`replay_state_hash` varchar(64),
	`diff_json` json,
	`replay_result_json` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rt_replay_comparisons_id` PRIMARY KEY(`id`),
	CONSTRAINT `rt_replay_comparison_identity` UNIQUE(`baseline_version`,`source_event_id`)
);
--> statement-breakpoint
ALTER TABLE `rt_source_events` ADD `cloud_received_at_ms` bigint;--> statement-breakpoint
ALTER TABLE `rt_strategy_versions` ADD `rt_strategy_evaluation_purpose` enum('candidate','parity_only','causality_audit') DEFAULT 'candidate' NOT NULL;--> statement-breakpoint
ALTER TABLE `rt_strategy_versions` ADD `eligible_for_adoption` boolean DEFAULT true NOT NULL;