CREATE TABLE `rt_signal_candidate_trades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`virtual_engine_version` varchar(64) NOT NULL,
	`candidate_id` int NOT NULL,
	`entry_source_event_id` varchar(128) NOT NULL,
	`trade_date` varchar(10) NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`route_id` varchar(96) NOT NULL,
	`rt_signal_candidate_trade_side` enum('long','short') NOT NULL,
	`entry_candle_time` varchar(5) NOT NULL,
	`entry_price` decimal(12,4) NOT NULL,
	`shares` int NOT NULL DEFAULT 100,
	`sl_pct` decimal(8,4) NOT NULL,
	`tp_pct` decimal(8,4) NOT NULL,
	`max_holding_minutes` int,
	`state_json` json NOT NULL,
	`exit_source_event_id` varchar(128),
	`exit_trade_date` varchar(10),
	`exit_candle_time` varchar(5),
	`exit_price` decimal(12,4),
	`exit_reason` varchar(64),
	`pnl` bigint,
	`realized_r` decimal(12,6),
	`mfe_pct` decimal(10,6),
	`mae_pct` decimal(10,6),
	`completed` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rt_signal_candidate_trades_id` PRIMARY KEY(`id`),
	CONSTRAINT `rt_signal_candidate_trade_identity` UNIQUE(`virtual_engine_version`,`candidate_id`)
);
--> statement-breakpoint
CREATE TABLE `rt_signal_candidates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`candidate_version` varchar(64) NOT NULL,
	`source_event_id` varchar(128) NOT NULL,
	`source_event_db_id` int NOT NULL,
	`engine_sequence` int NOT NULL,
	`trade_date` varchar(10) NOT NULL,
	`candle_time` varchar(5) NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`route_id` varchar(96) NOT NULL,
	`rt_signal_candidate_side` enum('long','short') NOT NULL,
	`signal_reason` text NOT NULL,
	`theoretical_entry_price` decimal(12,4) NOT NULL,
	`signal_quality_shares` int NOT NULL DEFAULT 100,
	`capital_shares` int NOT NULL,
	`required_margin` bigint NOT NULL,
	`margin_used_before` bigint NOT NULL,
	`margin_limit` bigint NOT NULL,
	`rt_signal_candidate_decision` enum('accepted','margin_block') NOT NULL,
	`sl_pct` decimal(8,4) NOT NULL,
	`tp_pct` decimal(8,4) NOT NULL,
	`max_holding_minutes` int,
	`session_exit_time` varchar(5),
	`profit_protection_json` json,
	`entry_observed_at_ms` bigint,
	`decision_at_ms` bigint NOT NULL,
	`input_json` json NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rt_signal_candidates_id` PRIMARY KEY(`id`),
	CONSTRAINT `rt_signal_candidate_identity` UNIQUE(`candidate_version`,`source_event_id`)
);
