import {
  bigint,
  boolean,
  decimal,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * デイリーシミュレーションレポート（1日1レコード）
 * 毎平日の架空トレーディング結果を保存する
 */
export const dailyReports = mysqlTable("daily_reports", {
  id: int("id").autoincrement().primaryKey(),
  /** 対象日 (YYYY-MM-DD) */
  reportDate: varchar("reportDate", { length: 10 }).notNull().unique(),
  /** 総元金（円） */
  totalInitialCapital: bigint("totalInitialCapital", { mode: "number" }).notNull(),
  /** 検証後評価額合計（円） */
  totalFinalBalance: bigint("totalFinalBalance", { mode: "number" }).notNull(),
  /** 総合損益額（円） */
  totalProfitAmount: bigint("totalProfitAmount", { mode: "number" }).notNull(),
  /** 総合利益率（小数） */
  totalProfitRate: decimal("totalProfitRate", { precision: 10, scale: 6 }).notNull(),
  /** 全銘柄の勝ちトレード数 */
  totalWinCount: int("totalWinCount").notNull().default(0),
  /** 全銘柄の負けトレード数 */
  totalLossCount: int("totalLossCount").notNull().default(0),
  /** 全体勝率（小数） */
  overallWinRate: decimal("overallWinRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 使用したRSI上限パラメータ */
  rsiUpper: int("rsiUpper").notNull().default(70),
  /** 使用したRSI下限パラメータ */
  rsiLower: int("rsiLower").notNull().default(30),
  /** 使用した損切り率（%） */
  stopLossPercent: decimal("stopLossPercent", { precision: 5, scale: 2 }).notNull().default("1.5"),
  /** AIによる総合分析コメント */
  aiSummary: text("aiSummary"),
  /** スケジューラーによる自動生成かどうか */
  isAutoGenerated: boolean("isAutoGenerated").notNull().default(false),
  /** スケジュールタスクUID */
  scheduleCronTaskUid: varchar("scheduleCronTaskUid", { length: 65 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type DailyReport = typeof dailyReports.$inferSelect;
export type InsertDailyReport = typeof dailyReports.$inferInsert;

/**
 * 銘柄別シミュレーション結果（1日×10銘柄 = 10レコード）
 */
export const stockReports = mysqlTable("stock_reports", {
  id: int("id").autoincrement().primaryKey(),
  /** 親レポートID */
  dailyReportId: int("dailyReportId").notNull(),
  /** 銘柄コード */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 銘柄名 */
  name: varchar("name", { length: 50 }).notNull(),
  /** 元金（円） */
  initialCapital: bigint("initialCapital", { mode: "number" }).notNull(),
  /** 最終評価額（円） */
  finalBalance: bigint("finalBalance", { mode: "number" }).notNull(),
  /** 損益額（円） */
  profitAmount: bigint("profitAmount", { mode: "number" }).notNull(),
  /** 利益率（小数） */
  profitRate: decimal("profitRate", { precision: 10, scale: 6 }).notNull(),
  /** 総取引回数 */
  tradesCount: int("tradesCount").notNull().default(0),
  /** 勝ちトレード数 */
  winCount: int("winCount").notNull().default(0),
  /** 勝率（小数） */
  winRate: decimal("winRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 取引履歴 JSON */
  trades: json("trades").notNull().$type<TradeRecord[]>(),
  /** 損失原因リスト JSON */
  lossCauses: json("lossCauses").notNull().$type<string[]>(),
  /** 対策リスト JSON */
  countermeasures: json("countermeasures").notNull().$type<string[]>(),
  /** シグナル一覧 JSON - 買い/売りタイミング・理由の詳細 */
  signals: json("signals").$type<SignalRecord[]>(),
  /** 実データ使用フラグ */
  isRealData: boolean("isRealData").notNull().default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type StockReport = typeof stockReports.$inferSelect;
export type InsertStockReport = typeof stockReports.$inferInsert;

/**
 * シグナルレコード（JSON内に格納） - 実際のチャートと同様の買い/売りタイミング詳細
 */
export interface SignalRecord {
  time: string;
  type: "buy" | "sell" | "warn" | "short" | "cover";
  price: number;
  ma5: number | null;
  ma25: number | null;
  rsi: number | null;
  reason: string;
}

/**
 * 取引レコード（JSON内に格納）
 */
export interface TradeRecord {
  time: string;
  type: "buy" | "sell" | "short" | "cover";
  price: number;
  shares: number;
  totalAmount: number;
  profit?: number;
  profitRate?: number;
}

/**
 * アルゴリズム改善履歴
 * 失敗原因の蓄積と対策の適用を追跡する
 */
export const algorithmImprovements = mysqlTable("algorithm_improvements", {
  id: int("id").autoincrement().primaryKey(),
  /** 参照した日次レポートID */
  dailyReportId: int("dailyReportId").notNull(),
  /** 改善前のRSI上限 */
  prevRsiUpper: int("prevRsiUpper").notNull(),
  /** 改善前のRSI下限 */
  prevRsiLower: int("prevRsiLower").notNull(),
  /** 改善前の損切り率 */
  prevStopLossPercent: decimal("prevStopLossPercent", { precision: 5, scale: 2 }).notNull(),
  /** 改善後のRSI上限 */
  newRsiUpper: int("newRsiUpper").notNull(),
  /** 改善後のRSI下限 */
  newRsiLower: int("newRsiLower").notNull(),
  /** 改善後の損切り率 */
  newStopLossPercent: decimal("newStopLossPercent", { precision: 5, scale: 2 }).notNull(),
  /** 改善理由（AIによる分析） */
  improvementReason: text("improvementReason").notNull(),
  /** 適用日 */
  appliedAt: timestamp("appliedAt").defaultNow().notNull(),
});

export type AlgorithmImprovement = typeof algorithmImprovements.$inferSelect;
export type InsertAlgorithmImprovement = typeof algorithmImprovements.$inferInsert;

/**
 * 現在のアルゴリズムパラメータ設定（1レコードのみ）
 */
export const algorithmConfig = mysqlTable("algorithm_config", {
  id: int("id").autoincrement().primaryKey(),
  /** RSI買われすぎ閾値 */
  rsiUpper: int("rsiUpper").notNull().default(70),
  /** RSI売られすぎ閾値 */
  rsiLower: int("rsiLower").notNull().default(30),
  /** 損切り率（%） */
  stopLossPercent: decimal("stopLossPercent", { precision: 5, scale: 2 }).notNull().default("1.5"),
  /** 大口判定の基準出来高 */
  largeVolumeThreshold: int("largeVolumeThreshold").notNull().default(8000),
  /** 累計勝率（直近30日） */
  recentWinRate: decimal("recentWinRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 累計損益率（直近30日） */
  recentProfitRate: decimal("recentProfitRate", { precision: 10, scale: 6 }).notNull().default("0"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AlgorithmConfig = typeof algorithmConfig.$inferSelect;
export type InsertAlgorithmConfig = typeof algorithmConfig.$inferInsert;

/**
 * 仮想売買（ペーパートレード）記録
 * ユーザーがリアルタイムで「仮買い／仮売り」をボタンで記録するための個人取引履歴。
 * 実際の発注は行わない練習用途。
 */
export const paperTrades = mysqlTable("paper_trades", {
  id: int("id").autoincrement().primaryKey(),
  /** 取引したユーザーのID */
  userId: int("userId").notNull(),
  /** 銘柄コード（例: 9984） */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 銘柄名 */
  symbolName: varchar("symbolName", { length: 50 }).notNull(),
  /** ポジション方向: long=買い / short=空売り */
  side: mysqlEnum("side", ["long", "short"]).notNull(),
  /** エントリー価格（円） */
  entryPrice: decimal("entryPrice", { precision: 12, scale: 2 }).notNull(),
  /** 株数 */
  quantity: int("quantity").notNull(),
  /** ステータス: open=保有中 / closed=決済済み */
  status: mysqlEnum("status", ["open", "closed"]).notNull().default("open"),
  /** 決済価格（円）- 決済時のみ */
  exitPrice: decimal("exitPrice", { precision: 12, scale: 2 }),
  /** 損益額（円）- 決済時に計算 */
  pnl: bigint("pnl", { mode: "number" }),
  /** メモ（任意） */
  note: text("note"),
  /** エントリー時刻 */
  entryAt: timestamp("entryAt").defaultNow().notNull(),
  /** 決済時刻 */
  exitAt: timestamp("exitAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PaperTrade = typeof paperTrades.$inferSelect;
export type InsertPaperTrade = typeof paperTrades.$inferInsert;

/**
 * kabuステーション® プラン期限管理
 * Premiumプランの有効期限と継続条件の達成状況を管理する
 */
export const kabuPlanSettings = mysqlTable("kabu_plan_settings", {
  id: int("id").autoincrement().primaryKey(),
  /** 現在のプラン種別 */
  planType: mysqlEnum("planType", ["normal", "professional", "premium"]).notNull().default("professional"),
  /** プラン有効期限（YYYY-MM-DD） */
  planExpiresAt: varchar("planExpiresAt", { length: 10 }).notNull(),
  /** リマインドメール送信済みフラグ */
  reminderSent: boolean("reminderSent").notNull().default(false),
  /** リマインドメール送信日時 */
  reminderSentAt: timestamp("reminderSentAt"),
  /** メモ（継続条件の達成状況など） */
  note: text("note"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type KabuPlanSettings = typeof kabuPlanSettings.$inferSelect;
export type InsertKabuPlanSettings = typeof kabuPlanSettings.$inferInsert;

/**
 * リアルタイム受信1分足ローソク足ログ
 * Windowsスクリプトから送信された1分足OHLCVを記録する
 */
export const rtCandles = mysqlTable("rt_candles", {
  id: int("id").autoincrement().primaryKey(),
  /** 銘柄コード（例: 6976） */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull(),
  /** 1分足の時刻 (HH:MM) */
  candleTime: varchar("candleTime", { length: 5 }).notNull(),
  /** 始値（円） */
  open: decimal("open", { precision: 12, scale: 2 }).notNull(),
  /** 高値（円） */
  high: decimal("high", { precision: 12, scale: 2 }).notNull(),
  /** 低値（円） */
  low: decimal("low", { precision: 12, scale: 2 }).notNull(),
  /** 終値（円） */
  close: decimal("close", { precision: 12, scale: 2 }).notNull(),
  /** 出来高 */
  volume: bigint("volume", { mode: "number" }).notNull().default(0),
  /** 板情報スナップショット JSON（板圧力・大口注文・成行比率） */
  boardSnapshot: json("boardSnapshot").$type<BoardSnapshot | null>(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export interface BoardSnapshot {
  buyPressureRatio: number;   // 買い板合計 / 売り板合計
  largeBuyWall: boolean;      // 大口買い壁あり
  largeSellWall: boolean;     // 大口売り壁あり
  marketOrderRatio: number;   // 成行注文比率
  signal: "buy_pressure" | "sell_pressure" | "large_buy_wall" | "large_sell_wall" | "market_surge" | "neutral";
  // v5拡張フィールド（パターン6.14対応）
  largeAskWallRatio?: number;        // 売り板の最大注文 / 平均注文 の倍率
  largeBidWallRatio?: number;        // 買い板の最大注文 / 平均注文 の倍率
  largeAskWallPrice?: number | null; // 大口売り注文の価格
  largeBidWallPrice?: number | null; // 大口買い注文の価格
  nearAskWallPct?: number | null;    // 現値から大口売り注文までの距離（%）
  nearBidWallPct?: number | null;    // 現値から大口買い注文までの距離（%）
  marketOrderDirection?: "buy" | "sell" | "neutral"; // 成り行き注文の方向
  askCancelDetected?: boolean;       // 売り板の大口キャンセル検出
  bidCancelDetected?: boolean;       // 買い板の大口キャンセル検出
  icebergAskDetected?: boolean;      // 売りアイスバーグ注文検出
  icebergBidDetected?: boolean;      // 買いアイスバーグ注文検出
  totalAskQty?: number;              // 売り板合計数量
  totalBidQty?: number;              // 買い板合計数量
  // v8拡張: 10秒リングバッファ集約結果
  icebergAskCount?: number;          // 直近1分間のアイスバーグ検出回数（ask側）
  icebergBidCount?: number;          // 直近1分間のアイスバーグ検出回数（bid側）
  cancelAskCount?: number;           // 直近1分間のキャンセル検出回数（ask側）
  cancelBidCount?: number;           // 直近1分間のキャンセル検出回数（bid側）
  avgBprIn10s?: number;              // 直近1分間のBPR平均（10秒間隔集約）
  bprDeltaIn10s?: number;            // 直近1分間のBPR変化幅
  largeTradeDirection?: "buy" | "sell" | "neutral"; // 大口約定方向推定（10秒集約）
  boardSampleCount?: number;         // 集約サンプル数
}

export type RtCandle = typeof rtCandles.$inferSelect;
export type InsertRtCandle = typeof rtCandles.$inferInsert;

/**
 * リアルタイムシミュレーション取引ログ
 * 1分足受信時にシグナル判定して記録する架空取引
 */
export const rtTrades = mysqlTable("rt_trades", {
  id: int("id").autoincrement().primaryKey(),
  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull(),
  /** 銘柄コード */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 銘柄名 */
  symbolName: varchar("symbolName", { length: 50 }).notNull(),
  /** 取引種別: buy=買い / sell=売り / short=空売り / cover=買い戻し */
  action: mysqlEnum("action", ["buy", "sell", "short", "cover"]).notNull(),
  /** 約定価格（円） */
  price: decimal("price", { precision: 12, scale: 2 }).notNull(),
  /** 株数 */
  shares: int("shares").notNull(),
  /** 取引金額（円） */
  amount: bigint("amount", { mode: "number" }).notNull(),
  /** 損益額（決済時のみ、円） */
  pnl: bigint("pnl", { mode: "number" }),
  /** シグナル理由 */
  reason: text("reason").notNull(),
  /** エントリー/決済時刻 (HH:MM) */
  tradeTime: varchar("tradeTime", { length: 5 }).notNull(),
  /** ポジション方向: long / short */
  side: mysqlEnum("side", ["long", "short"]).notNull(),
  /** 板情報シグナル（あれば） */
  boardSignal: varchar("boardSignal", { length: 30 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type RtTrade = typeof rtTrades.$inferSelect;
export type InsertRtTrade = typeof rtTrades.$inferInsert;

/**
 * リアルタイムシミュレーション日次サマリー
 * 大引け後に集計して保存する当日の成績
 */
export const rtDailySummaries = mysqlTable("rt_daily_summaries", {
  id: int("id").autoincrement().primaryKey(),
  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull().unique(),
  /** 元金（円） */
  initialCapital: bigint("initialCapital", { mode: "number" }).notNull(),
  /** 当日損益合計（円） */
  totalPnl: bigint("totalPnl", { mode: "number" }).notNull().default(0),
  /** 取引回数 */
  tradesCount: int("tradesCount").notNull().default(0),
  /** 勝ちトレード数 */
  winCount: int("winCount").notNull().default(0),
  /** 負けトレード数 */
  lossCount: int("lossCount").notNull().default(0),
  /** 受信した1分足本数 */
  candlesReceived: int("candlesReceived").notNull().default(0),
  /** レポートメール送信済みフラグ */
  reportSent: boolean("reportSent").notNull().default(false),
  /** レポートメール送信日時 */
  reportSentAt: timestamp("reportSentAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type RtDailySummary = typeof rtDailySummaries.$inferSelect;
export type InsertRtDailySummary = typeof rtDailySummaries.$inferInsert;

/**
 * 自動売買: 発注指示テーブル
 * クラウド（orderBridge）がrt_tradesの新規エントリー/決済を検知して生成し、
 * ローカルPC（kabu_order_executor.py）がポーリングして実行する。
 *
 * ライフサイクル:
 *   pending → sent → executed/failed
 *   pending → expired (60秒超過、entryのみ)
 *   pending → cancelled (緊急停止時)
 */
export const orderInstructions = mysqlTable("order_instructions", {
  id: int("id").autoincrement().primaryKey(),

  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull(),

  /** 銘柄コード（例: 9984） */
  symbol: varchar("symbol", { length: 10 }).notNull(),

  /** 銘柄名 */
  symbolName: varchar("symbolName", { length: 50 }).notNull(),

  /**
   * 売買方向
   * buy: 信用新規買い (Side="2", CashMargin=2)
   * sell: 信用返済売り (Side="1", CashMargin=3) — LONG決済
   * short: 信用新規売り (Side="1", CashMargin=2)
   * cover: 信用返済買い (Side="2", CashMargin=3) — SHORT決済
   */
  side: mysqlEnum("oi_side", ["buy", "sell", "short", "cover"]).notNull(),

  /**
   * 指示種別
   * entry: 新規建て（60秒で期限切れ）
   * exit: 決済（期限なし、必ず実行）
   * force_close: 大引け強制決済（期限なし、必ず実行）
   */
  instructionType: mysqlEnum("oi_instruction_type", ["entry", "exit", "force_close"]).notNull(),

  /** 注文数量（株） */
  qty: int("qty").notNull().default(100),

  /**
   * ステータス
   * pending: 未実行（executorがポーリングで取得する対象）
   * sent: KABU APIに送信済み（約定待ち）
   * executed: 約定完了
   * failed: 発注失敗（APIエラー等）
   * expired: 期限切れ（entryのみ、60秒超過）
   * cancelled: 緊急停止等でキャンセル
   */
  status: mysqlEnum("oi_status", ["pending", "sent", "executed", "failed", "expired", "cancelled"]).notNull().default("pending"),

  /** シグナル理由（realtimeSimEngineのreason） */
  reason: text("reason").notNull(),

  /** 参照価格（シグナル発生時の価格、実際の約定価格ではない） */
  referencePrice: decimal("referencePrice", { precision: 12, scale: 2 }).notNull(),

  /** 期限切れ日時（entryのみ: createdAt + 60秒、exit/force_closeはnull） */
  expiresAt: timestamp("expiresAt"),

  /** KABU Station APIから返されたOrderId */
  kabuOrderId: varchar("kabuOrderId", { length: 30 }),

  /** 実約定価格（約定確認後に記録） */
  executedPrice: decimal("executedPrice", { precision: 12, scale: 2 }),

  /** 約定日時 */
  executedAt: timestamp("executedAt"),

  /** 損益（決済時のみ、円） */
  pnl: bigint("pnl", { mode: "number" }),

  /** 対応するrt_tradesのID（FK参照用、外部キー制約なし） */
  rtTradeId: int("rtTradeId"),

  /** エラーメッセージ（failed時） */
  errorMessage: text("errorMessage"),

  /** ドライランモードで生成されたか */
  isDryRun: boolean("isDryRun").notNull().default(true),

  /** executor側のログ（JSON形式、デバッグ用） */
  executorLog: json("executorLog").$type<Record<string, unknown> | null>(),

  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type OrderInstruction = typeof orderInstructions.$inferSelect;
export type InsertOrderInstruction = typeof orderInstructions.$inferInsert;

/**
 * 自動売買: 日次リスク管理テーブル
 * 1日1レコード。日次の損益上限・緊急停止状態を管理する。
 */
export const autoTradeDaily = mysqlTable("auto_trade_daily", {
  id: int("id").autoincrement().primaryKey(),

  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull().unique(),

  /** 当日の実現損益合計（円） */
  realizedPnl: bigint("realizedPnl", { mode: "number" }).notNull().default(0),

  /** 当日の取引回数 */
  tradeCount: int("tradeCount").notNull().default(0),

  /** 日次損失上限（円、負の値）- これを超えたら新規エントリー停止 */
  dailyLossLimit: bigint("dailyLossLimit", { mode: "number" }).notNull().default(-100000),

  /** 取引有効フラグ（falseで全発注停止） */
  tradingEnabled: boolean("tradingEnabled").notNull().default(true),

  /** 緊急停止フラグ（手動またはリスク管理で停止） */
  emergencyStop: boolean("emergencyStop").notNull().default(false),

  /** 緊急停止理由 */
  emergencyStopReason: text("emergencyStopReason"),

  /** ドライランモード（true=実際の発注を行わない） */
  isDryRun: boolean("isDryRun").notNull().default(true),

  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AutoTradeDaily = typeof autoTradeDaily.$inferSelect;
export type InsertAutoTradeDaily = typeof autoTradeDaily.$inferInsert;

/**
 * 3山v2シグナルログ（観測のみ、実エントリーなし）
 * 3山切り下げ(SHORT) / 3谷切り上げ(LONG) のシグナルを検出した際にログ記録し、
 * 仮想的にTP/SL/EODの結果を追跡する。
 */
export const rt3peakSignals = mysqlTable("rt_3peak_signals", {
  id: int("id").autoincrement().primaryKey(),
  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull(),
  /** 銘柄コード */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** シグナル方向: short=3山切り下げ / long=3谷切り上げ */
  direction: mysqlEnum("direction_3peak", ["short", "long"]).notNull(),
  /** シグナル検出時刻 (HH:MM) */
  signalTime: varchar("signalTime", { length: 5 }).notNull(),
  /** 仮想エントリー価格（次足close） */
  entryPrice: decimal("entryPrice", { precision: 12, scale: 2 }).notNull(),
  /** 仮想決済価格（TP/SL/EOD時） */
  exitPrice: decimal("exitPrice", { precision: 12, scale: 2 }),
  /** 決済時刻 (HH:MM) */
  exitTime: varchar("exitTime", { length: 5 }),
  /** 決済理由: tp/sl/eod/pending */
  exitReason: mysqlEnum("exit_reason_3peak", ["tp", "sl", "eod", "pending"]).notNull().default("pending"),
  /** 仮想損益（円） */
  virtualPnl: bigint("virtualPnl", { mode: "number" }),
  /** 仮想株数 */
  shares: int("shares").notNull(),
  /** 保有足数 */
  holdBars: int("holdBars"),
  /** 連続切り下げ/切り上げ回数 */
  consecutiveCount: int("consecutiveCount").notNull(),
  /** シグナル詳細（デバッグ用） */
  details: text("details"),
  /** レポート通知済みフラグ */
  reportSent: boolean("reportSent").notNull().default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Rt3peakSignal = typeof rt3peakSignals.$inferSelect;
export type InsertRt3peakSignal = typeof rt3peakSignals.$inferInsert;

// ============================================================
// スコア0+信頼度強ブロック記録テーブル
// ============================================================
export const rtScore0Blocks = mysqlTable("rt_score0_blocks", {
  id: int("id").autoincrement().primaryKey(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  side: varchar("side", { length: 5 }).notNull(),
  signalReason: varchar("signal_reason", { length: 200 }).notNull(),
  entryPrice: decimal("entry_price", { precision: 12, scale: 2 }).notNull(),
  boardScore: int("board_score").notNull().default(0),
  confidence: varchar("confidence", { length: 10 }).notNull().default("strong"),
  context: varchar("context", { length: 50 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type RtScore0Block = typeof rtScore0Blocks.$inferSelect;
export type InsertRtScore0Block = typeof rtScore0Blocks.$inferInsert;

/**
 * 6976候補B DRY_RUN監査イベント。
 * 確認失敗・ATR/証拠金等の共通ゲート拒否を再起動後も16時報告へ復元する。
 */
export const rtTaiyoCandidateBEvents = mysqlTable("rt_taiyo_candidate_b_events", {
  id: int("id").autoincrement().primaryKey(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  eventType: mysqlEnum("taiyo_candidate_b_event_type", ["confirmation_rejected", "engine_rejected"]).notNull(),
  side: mysqlEnum("taiyo_candidate_b_event_side", ["long", "short"]).notNull(),
  triggerTime: varchar("trigger_time", { length: 5 }).notNull(),
  rejectionCodes: json("rejection_codes").$type<string[] | null>(),
  detail: text("detail"),
  referencePrice: decimal("reference_price", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  eventIdentity: uniqueIndex("rt_taiyo_candidate_b_event_identity").on(
    table.tradeDate,
    table.symbol,
    table.candleTime,
    table.eventType,
    table.side,
    table.triggerTime,
  ),
}));

export type RtTaiyoCandidateBEvent = typeof rtTaiyoCandidateBEvents.$inferSelect;
export type InsertRtTaiyoCandidateBEvent = typeof rtTaiyoCandidateBEvents.$inferInsert;

/**
 * 6526確認型LONG DRY_RUN監査イベント。
 * 確認失敗・ATR/証拠金等の共通ゲート拒否を再起動後も16時報告へ復元する。
 */
export const rtSocionextConfirmedLongEvents = mysqlTable("rt_socionext_confirmed_long_events", {
  id: int("id").autoincrement().primaryKey(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  eventType: mysqlEnum("socionext_confirmed_long_event_type", ["confirmation_rejected", "engine_rejected"]).notNull(),
  side: mysqlEnum("socionext_confirmed_long_event_side", ["long"]).notNull(),
  triggerTime: varchar("trigger_time", { length: 5 }).notNull(),
  rejectionCodes: json("rejection_codes").$type<string[] | null>(),
  detail: text("detail"),
  referencePrice: decimal("reference_price", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  eventIdentity: uniqueIndex("rt_socionext_confirmed_long_event_identity").on(
    table.tradeDate,
    table.symbol,
    table.candleTime,
    table.eventType,
    table.side,
    table.triggerTime,
  ),
}));

export type RtSocionextConfirmedLongEvent = typeof rtSocionextConfirmedLongEvents.$inferSelect;
export type InsertRtSocionextConfirmedLongEvent = typeof rtSocionextConfirmedLongEvents.$inferInsert;

/**
 * 3436専用SHORT DRY_RUN監査イベント。
 * ATR・証拠金等の共通ゲート拒否を再起動後も16時報告へ復元する。
 */
export const rtSumcoBreakdownShortEvents = mysqlTable("rt_sumco_breakdown_short_events", {
  id: int("id").autoincrement().primaryKey(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  eventType: mysqlEnum("sumco_breakdown_short_event_type", ["engine_rejected"]).notNull(),
  side: mysqlEnum("sumco_breakdown_short_event_side", ["short"]).notNull(),
  detail: text("detail"),
  referencePrice: decimal("reference_price", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  eventIdentity: uniqueIndex("rt_sumco_breakdown_short_event_identity").on(
    table.tradeDate,
    table.symbol,
    table.candleTime,
    table.eventType,
    table.side,
  ),
}));

export type RtSumcoBreakdownShortEvent = typeof rtSumcoBreakdownShortEvents.$inferSelect;
export type InsertRtSumcoBreakdownShortEvent = typeof rtSumcoBreakdownShortEvents.$inferInsert;

/**
 * 9984専用LONG DRY_RUN監査イベント。
 * ATR・証拠金等の共通ゲート拒否を再起動後も16時報告へ復元する。
 */
export const rtSoftbankBreakoutLongEvents = mysqlTable("rt_softbank_breakout_long_events", {
  id: int("id").autoincrement().primaryKey(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  eventType: mysqlEnum("softbank_breakout_long_event_type", ["engine_rejected"]).notNull(),
  side: mysqlEnum("softbank_breakout_long_event_side", ["long"]).notNull(),
  detail: text("detail"),
  referencePrice: decimal("reference_price", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  eventIdentity: uniqueIndex("rt_softbank_breakout_long_event_identity").on(
    table.tradeDate,
    table.symbol,
    table.candleTime,
    table.eventType,
    table.side,
  ),
}));

export type RtSoftbankBreakoutLongEvent = typeof rtSoftbankBreakoutLongEvents.$inferSelect;
export type InsertRtSoftbankBreakoutLongEvent = typeof rtSoftbankBreakoutLongEvents.$inferInsert;

/**
 * 285A確認型前場LONG DRY_RUN監査イベント。
 * ATR・証拠金等の共通ゲート拒否を再起動後も16時報告へ復元する。
 */
export const rtKioxiaConfirmedMorningLongEvents = mysqlTable("rt_kioxia_confirmed_morning_long_events", {
  id: int("id").autoincrement().primaryKey(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  eventType: mysqlEnum("kioxia_confirmed_morning_long_event_type", ["engine_rejected"]).notNull(),
  side: mysqlEnum("kioxia_confirmed_morning_long_event_side", ["long"]).notNull(),
  detail: text("detail"),
  referencePrice: decimal("reference_price", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  eventIdentity: uniqueIndex("rt_kioxia_confirmed_morning_long_event_identity").on(
    table.tradeDate,
    table.symbol,
    table.candleTime,
    table.eventType,
    table.side,
  ),
}));

export type RtKioxiaConfirmedMorningLongEvent = typeof rtKioxiaConfirmedMorningLongEvents.$inferSelect;
export type InsertRtKioxiaConfirmedMorningLongEvent = typeof rtKioxiaConfirmedMorningLongEvents.$inferInsert;

/**
 * 8035始値方向付き短期ブレイク DRY_RUN監査イベント。
 * ATR・証拠金等の共通ゲート拒否を再起動後も16時報告へ復元する。
 */
export const rtTelOpenDirectionBreakoutEvents = mysqlTable("rt_tel_open_direction_breakout_events", {
  id: int("id").autoincrement().primaryKey(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  eventType: mysqlEnum("tel_open_direction_breakout_event_type", ["engine_rejected"]).notNull(),
  side: mysqlEnum("tel_open_direction_breakout_event_side", ["long", "short"]).notNull(),
  detail: text("detail"),
  referencePrice: decimal("reference_price", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  eventIdentity: uniqueIndex("rt_tel_open_direction_breakout_event_identity").on(
    table.tradeDate,
    table.symbol,
    table.candleTime,
    table.eventType,
    table.side,
  ),
}));

export type RtTelOpenDirectionBreakoutEvent = typeof rtTelOpenDirectionBreakoutEvents.$inferSelect;
export type InsertRtTelOpenDirectionBreakoutEvent = typeof rtTelOpenDirectionBreakoutEvents.$inferInsert;

/**
 * 285A SHORTガード DRY_RUN監査イベント。
 * 反転SHORTのBPR不足、安全CB SHORTの出来高不足による当日終了を再起動後も復元する。
 */
export const rtKioxiaShortGuardEvents = mysqlTable("rt_kioxia_short_guard_events", {
  id: int("id").autoincrement().primaryKey(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  guardType: mysqlEnum("kioxia_short_guard_type", ["reversal_short_bpr", "safe_cb_volume"]).notNull(),
  side: mysqlEnum("kioxia_short_guard_side", ["short"]).notNull(),
  observedValue: decimal("observed_value", { precision: 12, scale: 6 }).notNull(),
  thresholdValue: decimal("threshold_value", { precision: 12, scale: 6 }).notNull(),
  averageVolume: decimal("average_volume", { precision: 16, scale: 4 }),
  zeroVolumeBars: int("zero_volume_bars").notNull().default(0),
  detail: text("detail"),
  referencePrice: decimal("reference_price", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  eventIdentity: uniqueIndex("rt_kioxia_short_guard_event_identity").on(
    table.tradeDate,
    table.symbol,
    table.candleTime,
    table.guardType,
  ),
}));

export type RtKioxiaShortGuardEvent = typeof rtKioxiaShortGuardEvents.$inferSelect;
export type InsertRtKioxiaShortGuardEvent = typeof rtKioxiaShortGuardEvents.$inferInsert;

/**
 * Windows relayから受信した生イベントの追記専用監査ログ。
 * source_event_idだけを一意にし、訂正足は新しいイベントとして保存する。
 */
export const rtSourceEvents = mysqlTable("rt_source_events", {
  id: int("id").autoincrement().primaryKey(),
  sourceEventId: varchar("source_event_id", { length: 128 }).notNull(),
  relaySessionId: varchar("relay_session_id", { length: 96 }).notNull(),
  eventSeq: int("event_seq").notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  payloadHash: varchar("payload_hash", { length: 64 }).notNull(),
  payloadJson: json("payload_json").notNull(),
  relayReceivedAtMs: bigint("relay_received_at_ms", { mode: "number" }),
  relaySentAtMs: bigint("relay_sent_at_ms", { mode: "number" }),
  cloudReceivedAtMs: bigint("cloud_received_at_ms", { mode: "number" }),
  correctedEventId: varchar("corrected_event_id", { length: 128 }),
  status: mysqlEnum("rt_source_event_status", ["processing", "processed", "failed", "payload_mismatch"]).notNull().default("processing"),
  resultAction: varchar("result_action", { length: 32 }),
  resultJson: json("result_json"),
  errorDetail: text("error_detail"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  processedAt: timestamp("processed_at"),
}, table => ({
  sourceIdentity: uniqueIndex("rt_source_events_source_identity").on(table.sourceEventId),
}));

export type RtSourceEvent = typeof rtSourceEvents.$inferSelect;
export type InsertRtSourceEvent = typeof rtSourceEvents.$inferInsert;

/**
 * 現行エンジンが確定したengineSequence順に、全シャドー版へ同じ入力を渡す永続キュー。
 * source eventの到着順ではなく現行状態更新順を正式順序とし、複数サーバーでも追い越しを防ぐ。
 */
export const rtShadowDispatchQueue = mysqlTable("rt_shadow_dispatch_queue", {
  id: int("id").autoincrement().primaryKey(),
  sourceEventId: varchar("source_event_id", { length: 128 }).notNull(),
  engineSequence: int("engine_sequence").notNull(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  inputJson: json("input_json").notNull(),
  status: mysqlEnum("rt_shadow_dispatch_status", ["pending", "processing", "processed", "error"]).notNull().default("pending"),
  claimToken: varchar("claim_token", { length: 64 }),
  leaseUntil: timestamp("lease_until"),
  attemptCount: int("attempt_count").notNull().default(0),
  lastError: text("last_error"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  processedAt: timestamp("processed_at"),
}, table => ({
  sourceIdentity: uniqueIndex("rt_shadow_dispatch_source_identity").on(table.sourceEventId),
  engineSequenceIdentity: uniqueIndex("rt_shadow_dispatch_engine_sequence_identity").on(table.engineSequence),
}));

export type RtShadowDispatchQueue = typeof rtShadowDispatchQueue.$inferSelect;
export type InsertRtShadowDispatchQueue = typeof rtShadowDispatchQueue.$inferInsert;

/** 収集開始前に固定する前向き評価の戦略版。 */
export const rtStrategyVersions = mysqlTable("rt_strategy_versions", {
  versionId: varchar("version_id", { length: 128 }).primaryKey(),
  strategyId: varchar("strategy_id", { length: 64 }).notNull(),
  baselineGitSha: varchar("baseline_git_sha", { length: 64 }).notNull(),
  buildGitSha: varchar("build_git_sha", { length: 64 }).notNull(),
  sourceTreeHash: varchar("source_tree_hash", { length: 64 }).notNull(),
  configHash: varchar("config_hash", { length: 64 }).notNull(),
  configJson: json("config_json").notNull(),
  learningCutoffDate: varchar("learning_cutoff_date", { length: 10 }).notNull(),
  evaluationStartDate: varchar("evaluation_start_date", { length: 10 }).notNull(),
  evaluationPurpose: mysqlEnum("rt_strategy_evaluation_purpose", ["candidate", "parity_only", "causality_audit"]).notNull().default("candidate"),
  eligibleForAdoption: boolean("eligible_for_adoption").notNull().default(true),
  status: mysqlEnum("rt_strategy_version_status", ["monitoring", "interim_continue", "eligible", "stopped", "insufficient"]).notNull().default("monitoring"),
  statusReason: text("status_reason"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});

export type RtStrategyVersion = typeof rtStrategyVersions.$inferSelect;
export type InsertRtStrategyVersion = typeof rtStrategyVersions.$inferInsert;

/** 戦略版・受信イベント・評価方式ごとの一度きりの判断記録。 */
export const rtForwardShadowEvents = mysqlTable("rt_forward_shadow_events", {
  id: int("id").autoincrement().primaryKey(),
  strategyVersion: varchar("strategy_version", { length: 128 }).notNull(),
  sourceEventId: varchar("source_event_id", { length: 128 }).notNull(),
  evaluationMode: mysqlEnum("rt_forward_evaluation_mode", ["signal_quality", "capital_constrained"]).notNull(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  resultType: mysqlEnum("rt_forward_result_type", ["no_signal", "pending", "entry", "hold", "exit", "rejected", "error"]).notNull(),
  decisionJson: json("decision_json").notNull(),
  stateHashBefore: varchar("state_hash_before", { length: 64 }).notNull(),
  stateHashAfter: varchar("state_hash_after", { length: 64 }).notNull(),
  claimToken: varchar("claim_token", { length: 64 }),
  claimUntil: timestamp("claim_until"),
  attemptCount: int("attempt_count").notNull().default(1),
  lastError: text("last_error"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  eventIdentity: uniqueIndex("rt_forward_shadow_event_identity").on(
    table.strategyVersion,
    table.sourceEventId,
    table.evaluationMode,
  ),
}));

export type RtForwardShadowEvent = typeof rtForwardShadowEvents.$inferSelect;
export type InsertRtForwardShadowEvent = typeof rtForwardShadowEvents.$inferInsert;

/** 全発火版と資金制約版が独立して復元する状態スナップショット。 */
export const rtForwardShadowStates = mysqlTable("rt_forward_shadow_states", {
  id: int("id").autoincrement().primaryKey(),
  strategyVersion: varchar("strategy_version", { length: 128 }).notNull(),
  evaluationMode: mysqlEnum("rt_forward_state_mode", ["signal_quality", "capital_constrained"]).notNull(),
  stateJson: json("state_json").notNull(),
  stateHash: varchar("state_hash", { length: 64 }).notNull(),
  lastSourceEventId: varchar("last_source_event_id", { length: 128 }),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, table => ({
  stateIdentity: uniqueIndex("rt_forward_shadow_state_identity").on(table.strategyVersion, table.evaluationMode),
}));

export type RtForwardShadowState = typeof rtForwardShadowStates.$inferSelect;
export type InsertRtForwardShadowState = typeof rtForwardShadowStates.$inferInsert;

/** strategyVersion・評価方式単位の短時間リース。複数サーバーでも状態更新を直列化する。 */
export const rtForwardShadowLocks = mysqlTable("rt_forward_shadow_locks", {
  id: int("id").autoincrement().primaryKey(),
  strategyVersion: varchar("strategy_version", { length: 128 }).notNull(),
  evaluationMode: mysqlEnum("rt_forward_lock_mode", ["signal_quality", "capital_constrained"]).notNull(),
  ownerToken: varchar("owner_token", { length: 64 }),
  leaseUntil: timestamp("lease_until"),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, table => ({
  lockIdentity: uniqueIndex("rt_forward_shadow_lock_identity").on(table.strategyVersion, table.evaluationMode),
}));

export type RtForwardShadowLock = typeof rtForwardShadowLocks.$inferSelect;
export type InsertRtForwardShadowLock = typeof rtForwardShadowLocks.$inferInsert;

/** 次足始値を使った前向きシャドー取引。orderBridgeから完全分離する。 */
export const rtForwardShadowTrades = mysqlTable("rt_forward_shadow_trades", {
  id: int("id").autoincrement().primaryKey(),
  strategyVersion: varchar("strategy_version", { length: 128 }).notNull(),
  evaluationMode: mysqlEnum("rt_forward_trade_mode", ["signal_quality", "capital_constrained"]).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  side: mysqlEnum("rt_forward_trade_side", ["long", "short"]).notNull(),
  entrySourceEventId: varchar("entry_source_event_id", { length: 128 }).notNull(),
  entryTradeDate: varchar("entry_trade_date", { length: 10 }).notNull(),
  signalCandleTime: varchar("signal_candle_time", { length: 5 }).notNull(),
  entryCandleTime: varchar("entry_candle_time", { length: 5 }).notNull(),
  theoreticalSignalPrice: decimal("theoretical_signal_price", { precision: 12, scale: 4 }).notNull(),
  entryPrice: decimal("entry_price", { precision: 12, scale: 4 }).notNull(),
  shares: int("shares").notNull(),
  slPct: decimal("sl_pct", { precision: 8, scale: 4 }).notNull(),
  tpPct: decimal("tp_pct", { precision: 8, scale: 4 }).notNull(),
  exitSourceEventId: varchar("exit_source_event_id", { length: 128 }),
  exitTradeDate: varchar("exit_trade_date", { length: 10 }),
  exitCandleTime: varchar("exit_candle_time", { length: 5 }),
  exitPrice: decimal("exit_price", { precision: 12, scale: 4 }),
  exitReason: varchar("exit_reason", { length: 64 }),
  pnl: int("pnl"),
  pnlAfterAdverseExit: int("pnl_after_adverse_exit"),
  realizedR: decimal("realized_r", { precision: 12, scale: 6 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  closedAt: timestamp("closed_at"),
}, table => ({
  tradeIdentity: uniqueIndex("rt_forward_shadow_trade_identity").on(
    table.strategyVersion,
    table.evaluationMode,
    table.entrySourceEventId,
  ),
}));

export type RtForwardShadowTrade = typeof rtForwardShadowTrades.$inferSelect;
export type InsertRtForwardShadowTrade = typeof rtForwardShadowTrades.$inferInsert;

/** 現行リアルタイム状態機械をサーバー間でも一列に実行する短時間リース。 */
export const rtCurrentEngineLocks = mysqlTable("rt_current_engine_locks", {
  id: int("id").autoincrement().primaryKey(),
  lockName: varchar("lock_name", { length: 64 }).notNull(),
  ownerToken: varchar("owner_token", { length: 64 }),
  leaseUntil: timestamp("lease_until"),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, table => ({
  lockIdentity: uniqueIndex("rt_current_engine_lock_identity").on(table.lockName),
}));

export type RtCurrentEngineLock = typeof rtCurrentEngineLocks.$inferSelect;
export type InsertRtCurrentEngineLock = typeof rtCurrentEngineLocks.$inferInsert;

/**
 * 現行DRY_RUNが実際に状態更新した順序と判断前後状態を保存する追記専用台帳。
 * idがengineSequenceであり、source eventのDB受信順とは別に扱う。
 */
export const rtRealtimeDecisionEvents = mysqlTable("rt_realtime_decision_events", {
  id: int("id").autoincrement().primaryKey(),
  sourceEventDbId: int("source_event_db_id").notNull(),
  sourceEventId: varchar("source_event_id", { length: 128 }).notNull(),
  relaySessionId: varchar("relay_session_id", { length: 96 }).notNull(),
  eventSeq: int("event_seq").notNull(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  decisionStartedAtMs: bigint("decision_started_at_ms", { mode: "number" }).notNull(),
  decisionCompletedAtMs: bigint("decision_completed_at_ms", { mode: "number" }).notNull(),
  resultType: mysqlEnum("rt_realtime_decision_result", ["no_signal", "pending", "rejected", "entry", "hold", "exit", "error"]).notNull(),
  routeId: varchar("route_id", { length: 96 }),
  side: mysqlEnum("rt_realtime_decision_side", ["long", "short"]),
  reason: text("reason"),
  inputHash: varchar("input_hash", { length: 64 }).notNull(),
  stateBeforeJson: json("state_before_json").notNull(),
  stateAfterJson: json("state_after_json").notNull(),
  stateHashBefore: varchar("state_hash_before", { length: 64 }).notNull(),
  stateHashAfter: varchar("state_hash_after", { length: 64 }).notNull(),
  signalReferencePrice: decimal("signal_reference_price", { precision: 12, scale: 4 }),
  marketObservedPrice: decimal("market_observed_price", { precision: 12, scale: 4 }),
  boardPriceTime: varchar("board_price_time", { length: 40 }),
  executablePriceProxy: decimal("executable_price_proxy", { precision: 12, scale: 4 }),
  simulatedBarFillPrice: decimal("simulated_bar_fill_price", { precision: 12, scale: 4 }),
  brokerExecutionPrice: decimal("broker_execution_price", { precision: 12, scale: 4 }),
  shares: int("shares"),
  amount: bigint("amount", { mode: "number" }),
  marginUsedBefore: bigint("margin_used_before", { mode: "number" }),
  marginUsedAfter: bigint("margin_used_after", { mode: "number" }),
  causalityStatus: mysqlEnum("rt_realtime_causality_status", ["pass", "violation", "unverified", "not_applicable"]).notNull().default("unverified"),
  causalityReason: text("causality_reason"),
  resultJson: json("result_json").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  sourceIdentity: uniqueIndex("rt_realtime_decision_source_identity").on(table.sourceEventId),
}));

export type RtRealtimeDecisionEvent = typeof rtRealtimeDecisionEvents.$inferSelect;
export type InsertRtRealtimeDecisionEvent = typeof rtRealtimeDecisionEvents.$inferInsert;

/** strategyVersionごとに実時現行と固定版再生を項目別比較した結果。 */
export const rtReplayComparisons = mysqlTable("rt_replay_comparisons", {
  id: int("id").autoincrement().primaryKey(),
  baselineVersion: varchar("baseline_version", { length: 64 }).notNull(),
  sourceEventDbId: int("source_event_db_id").notNull(),
  sourceEventId: varchar("source_event_id", { length: 128 }).notNull(),
  engineSequence: int("engine_sequence"),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  matchStatus: mysqlEnum("rt_replay_match_status", ["match", "mismatch", "skipped", "error"]).notNull(),
  isFirstMismatch: boolean("is_first_mismatch").notNull().default(false),
  mismatchType: varchar("mismatch_type", { length: 64 }),
  realtimeDecisionId: int("realtime_decision_id"),
  realtimeStateHash: varchar("realtime_state_hash", { length: 64 }),
  replayStateHash: varchar("replay_state_hash", { length: 64 }),
  diffJson: json("diff_json"),
  replayResultJson: json("replay_result_json"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  comparisonIdentity: uniqueIndex("rt_replay_comparison_identity").on(table.baselineVersion, table.sourceEventId),
}));

export type RtReplayComparison = typeof rtReplayComparisons.$inferSelect;
export type InsertRtReplayComparison = typeof rtReplayComparisons.$inferInsert;

/** 10銘柄共有891万円を実受信順または同一分固定優先順位で配分した判断台帳。 */
export const rtPortfolioAuditEvents = mysqlTable("rt_portfolio_audit_events", {
  id: int("id").autoincrement().primaryKey(),
  portfolioVersion: varchar("portfolio_version", { length: 64 }).notNull(),
  mode: mysqlEnum("rt_portfolio_audit_mode", ["actual_receipt", "minute_normalized"]).notNull(),
  sourceEventId: varchar("source_event_id", { length: 128 }).notNull(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  batchKey: varchar("batch_key", { length: 32 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  routeId: varchar("route_id", { length: 96 }),
  side: mysqlEnum("rt_portfolio_audit_side", ["long", "short"]),
  priorityRank: int("priority_rank"),
  decision: mysqlEnum("rt_portfolio_audit_decision", ["accepted", "margin_block", "not_candidate", "missing", "closed"]).notNull(),
  shares: int("shares"),
  requiredMargin: bigint("required_margin", { mode: "number" }),
  marginUsedBefore: bigint("margin_used_before", { mode: "number" }).notNull().default(0),
  marginUsedAfter: bigint("margin_used_after", { mode: "number" }).notNull().default(0),
  blockerSourceEventId: varchar("blocker_source_event_id", { length: 128 }),
  blockerSymbol: varchar("blocker_symbol", { length: 10 }),
  detailJson: json("detail_json").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  portfolioIdentity: uniqueIndex("rt_portfolio_audit_identity").on(table.portfolioVersion, table.mode, table.sourceEventId),
}));

export type RtPortfolioAuditEvent = typeof rtPortfolioAuditEvents.$inferSelect;
export type InsertRtPortfolioAuditEvent = typeof rtPortfolioAuditEvents.$inferInsert;

/** MFE・MAE・経過後リターンなど、入口条件には使わない診断専用結果ラベル。 */
export const rtOutcomeLabels = mysqlTable("rt_outcome_labels", {
  id: int("id").autoincrement().primaryKey(),
  baselineVersion: varchar("baseline_version", { length: 64 }).notNull(),
  entrySourceEventId: varchar("entry_source_event_id", { length: 128 }).notNull(),
  exitSourceEventId: varchar("exit_source_event_id", { length: 128 }),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  routeId: varchar("route_id", { length: 96 }).notNull(),
  side: mysqlEnum("rt_outcome_label_side", ["long", "short"]).notNull(),
  entryPrice: decimal("entry_price", { precision: 12, scale: 4 }).notNull(),
  exitPrice: decimal("exit_price", { precision: 12, scale: 4 }),
  shares: int("shares").notNull(),
  mfePct: decimal("mfe_pct", { precision: 10, scale: 6 }),
  maePct: decimal("mae_pct", { precision: 10, scale: 6 }),
  after1mPct: decimal("after_1m_pct", { precision: 10, scale: 6 }),
  after3mPct: decimal("after_3m_pct", { precision: 10, scale: 6 }),
  after5mPct: decimal("after_5m_pct", { precision: 10, scale: 6 }),
  finalPnl: bigint("final_pnl", { mode: "number" }),
  counterfactualJson: json("counterfactual_json"),
  diagnosisOnly: boolean("diagnosis_only").notNull().default(true),
  completed: boolean("completed").notNull().default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, table => ({
  outcomeIdentity: uniqueIndex("rt_outcome_label_identity").on(table.baselineVersion, table.entrySourceEventId),
}));

export type RtOutcomeLabel = typeof rtOutcomeLabels.$inferSelect;
export type InsertRtOutcomeLabel = typeof rtOutcomeLabels.$inferInsert;

/** 原因候補と反実仮想影響。高確信度は未見シャドーで再現した場合だけ許可する。 */
export const rtDivergenceHypotheses = mysqlTable("rt_divergence_hypotheses", {
  id: int("id").autoincrement().primaryKey(),
  analysisVersion: varchar("analysis_version", { length: 64 }).notNull(),
  asOfDate: varchar("as_of_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  routeId: varchar("route_id", { length: 96 }).notNull(),
  causeCode: varchar("cause_code", { length: 64 }).notNull(),
  confidence: mysqlEnum("rt_divergence_confidence", ["low", "medium", "high"]).notNull(),
  realtimeLossCount: int("realtime_loss_count").notNull().default(0),
  historicalLossHit: int("historical_loss_hit").notNull().default(0),
  historicalWinHit: int("historical_win_hit").notNull().default(0),
  preventedLossYen: bigint("prevented_loss_yen", { mode: "number" }).notNull().default(0),
  lostWinYen: bigint("lost_win_yen", { mode: "number" }).notNull().default(0),
  followingTradeDeltaYen: bigint("following_trade_delta_yen", { mode: "number" }).notNull().default(0),
  portfolioDeltaYen: bigint("portfolio_delta_yen", { mode: "number" }).notNull().default(0),
  status: mysqlEnum("rt_divergence_status", ["observing", "shadow_candidate", "rejected"]).notNull().default("observing"),
  metricsJson: json("metrics_json").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, table => ({
  hypothesisIdentity: uniqueIndex("rt_divergence_hypothesis_identity").on(
    table.analysisVersion,
    table.asOfDate,
    table.symbol,
    table.routeId,
    table.causeCode,
  ),
}));

export type RtDivergenceHypothesis = typeof rtDivergenceHypotheses.$inferSelect;
export type InsertRtDivergenceHypothesis = typeof rtDivergenceHypotheses.$inferInsert;

/**
 * 現行エンジンが証拠金判定へ到達した全候補を、採用・margin blockを問わず保存する追記専用台帳。
 * 通常rt_trades・orderBridgeとは接続しない。
 */
export const rtSignalCandidates = mysqlTable("rt_signal_candidates", {
  id: int("id").autoincrement().primaryKey(),
  candidateVersion: varchar("candidate_version", { length: 64 }).notNull(),
  sourceEventId: varchar("source_event_id", { length: 128 }).notNull(),
  sourceEventDbId: int("source_event_db_id").notNull(),
  engineSequence: int("engine_sequence").notNull(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  candleTime: varchar("candle_time", { length: 5 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  routeId: varchar("route_id", { length: 96 }).notNull(),
  side: mysqlEnum("rt_signal_candidate_side", ["long", "short"]).notNull(),
  signalReason: text("signal_reason").notNull(),
  theoreticalEntryPrice: decimal("theoretical_entry_price", { precision: 12, scale: 4 }).notNull(),
  signalQualityShares: int("signal_quality_shares").notNull().default(100),
  capitalShares: int("capital_shares").notNull(),
  requiredMargin: bigint("required_margin", { mode: "number" }).notNull(),
  marginUsedBefore: bigint("margin_used_before", { mode: "number" }).notNull(),
  marginLimit: bigint("margin_limit", { mode: "number" }).notNull(),
  realtimeDecision: mysqlEnum("rt_signal_candidate_decision", ["accepted", "margin_block"]).notNull(),
  slPct: decimal("sl_pct", { precision: 8, scale: 4 }).notNull(),
  tpPct: decimal("tp_pct", { precision: 8, scale: 4 }).notNull(),
  maxHoldingMinutes: int("max_holding_minutes"),
  sessionExitTime: varchar("session_exit_time", { length: 5 }),
  profitProtectionJson: json("profit_protection_json"),
  entryObservedAtMs: bigint("entry_observed_at_ms", { mode: "number" }),
  decisionAtMs: bigint("decision_at_ms", { mode: "number" }).notNull(),
  inputJson: json("input_json").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => ({
  candidateIdentity: uniqueIndex("rt_signal_candidate_identity").on(table.candidateVersion, table.sourceEventId),
}));

export type RtSignalCandidate = typeof rtSignalCandidates.$inferSelect;
export type InsertRtSignalCandidate = typeof rtSignalCandidates.$inferInsert;

/**
 * rt_signal_candidatesを100株固定・証拠金制限なしで経路固有出口まで追跡した仮想取引。
 * 診断・前向き評価専用であり、通常取引・注文生成へ接続しない。
 */
export const rtSignalCandidateTrades = mysqlTable("rt_signal_candidate_trades", {
  id: int("id").autoincrement().primaryKey(),
  virtualEngineVersion: varchar("virtual_engine_version", { length: 64 }).notNull(),
  candidateId: int("candidate_id").notNull(),
  entrySourceEventId: varchar("entry_source_event_id", { length: 128 }).notNull(),
  tradeDate: varchar("trade_date", { length: 10 }).notNull(),
  symbol: varchar("symbol", { length: 10 }).notNull(),
  routeId: varchar("route_id", { length: 96 }).notNull(),
  side: mysqlEnum("rt_signal_candidate_trade_side", ["long", "short"]).notNull(),
  entryCandleTime: varchar("entry_candle_time", { length: 5 }).notNull(),
  entryPrice: decimal("entry_price", { precision: 12, scale: 4 }).notNull(),
  shares: int("shares").notNull().default(100),
  slPct: decimal("sl_pct", { precision: 8, scale: 4 }).notNull(),
  tpPct: decimal("tp_pct", { precision: 8, scale: 4 }).notNull(),
  maxHoldingMinutes: int("max_holding_minutes"),
  stateJson: json("state_json").notNull(),
  exitSourceEventId: varchar("exit_source_event_id", { length: 128 }),
  exitTradeDate: varchar("exit_trade_date", { length: 10 }),
  exitCandleTime: varchar("exit_candle_time", { length: 5 }),
  exitPrice: decimal("exit_price", { precision: 12, scale: 4 }),
  exitReason: varchar("exit_reason", { length: 64 }),
  pnl: bigint("pnl", { mode: "number" }),
  realizedR: decimal("realized_r", { precision: 12, scale: 6 }),
  mfePct: decimal("mfe_pct", { precision: 10, scale: 6 }),
  maePct: decimal("mae_pct", { precision: 10, scale: 6 }),
  completed: boolean("completed").notNull().default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, table => ({
  virtualTradeIdentity: uniqueIndex("rt_signal_candidate_trade_identity").on(
    table.virtualEngineVersion,
    table.candidateId,
  ),
}));

export type RtSignalCandidateTrade = typeof rtSignalCandidateTrades.$inferSelect;
export type InsertRtSignalCandidateTrade = typeof rtSignalCandidateTrades.$inferInsert;
