import {
  bigint,
  boolean,
  decimal,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * デイリーシミュレーションレポート（1日1レコード）
 * 毎平日の架空トレーディング結果を保存する
 */
export const dailyReports = mysqlTable("daily_reports", {
  id: int("id").autoincrement().primaryKey(),
  /** 対象日 (YYYY-MM-DD) */
  reportDate: varchar("reportDate", { length: 10 }).notNull().unique(),
  /** 総元金（円） */
  totalInitialCapital: bigint("totalInitialCapital", { mode: "number" }).notNull(),
  /** 検証後評価額合計（円） */
  totalFinalBalance: bigint("totalFinalBalance", { mode: "number" }).notNull(),
  /** 総合損益額（円） */
  totalProfitAmount: bigint("totalProfitAmount", { mode: "number" }).notNull(),
  /** 総合利益率（小数） */
  totalProfitRate: decimal("totalProfitRate", { precision: 10, scale: 6 }).notNull(),
  /** 全銘柄の勝ちトレード数 */
  totalWinCount: int("totalWinCount").notNull().default(0),
  /** 全銘柄の負けトレード数 */
  totalLossCount: int("totalLossCount").notNull().default(0),
  /** 全体勝率（小数） */
  overallWinRate: decimal("overallWinRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 使用したRSI上限パラメータ */
  rsiUpper: int("rsiUpper").notNull().default(70),
  /** 使用したRSI下限パラメータ */
  rsiLower: int("rsiLower").notNull().default(30),
  /** 使用した損切り率（%） */
  stopLossPercent: decimal("stopLossPercent", { precision: 5, scale: 2 }).notNull().default("1.5"),
  /** AIによる総合分析コメント */
  aiSummary: text("aiSummary"),
  /** スケジューラーによる自動生成かどうか */
  isAutoGenerated: boolean("isAutoGenerated").notNull().default(false),
  /** スケジュールタスクUID */
  scheduleCronTaskUid: varchar("scheduleCronTaskUid", { length: 65 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type DailyReport = typeof dailyReports.$inferSelect;
export type InsertDailyReport = typeof dailyReports.$inferInsert;

/**
 * 銘柄別シミュレーション結果（1日×10銘柄 = 10レコード）
 */
export const stockReports = mysqlTable("stock_reports", {
  id: int("id").autoincrement().primaryKey(),
  /** 親レポートID */
  dailyReportId: int("dailyReportId").notNull(),
  /** 銘柄コード */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 銘柄名 */
  name: varchar("name", { length: 50 }).notNull(),
  /** 元金（円） */
  initialCapital: bigint("initialCapital", { mode: "number" }).notNull(),
  /** 最終評価額（円） */
  finalBalance: bigint("finalBalance", { mode: "number" }).notNull(),
  /** 損益額（円） */
  profitAmount: bigint("profitAmount", { mode: "number" }).notNull(),
  /** 利益率（小数） */
  profitRate: decimal("profitRate", { precision: 10, scale: 6 }).notNull(),
  /** 総取引回数 */
  tradesCount: int("tradesCount").notNull().default(0),
  /** 勝ちトレード数 */
  winCount: int("winCount").notNull().default(0),
  /** 勝率（小数） */
  winRate: decimal("winRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 取引履歴 JSON */
  trades: json("trades").notNull().$type<TradeRecord[]>(),
  /** 損失原因リスト JSON */
  lossCauses: json("lossCauses").notNull().$type<string[]>(),
  /** 対策リスト JSON */
  countermeasures: json("countermeasures").notNull().$type<string[]>(),
  /** シグナル一覧 JSON - 買い/売りタイミング・理由の詳細 */
  signals: json("signals").$type<SignalRecord[]>(),
  /** 実データ使用フラグ */
  isRealData: boolean("isRealData").notNull().default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type StockReport = typeof stockReports.$inferSelect;
export type InsertStockReport = typeof stockReports.$inferInsert;

/**
 * シグナルレコード（JSON内に格納） - 実際のチャートと同様の買い/売りタイミング詳細
 */
export interface SignalRecord {
  time: string;
  type: "buy" | "sell" | "warn" | "short" | "cover";
  price: number;
  ma5: number | null;
  ma25: number | null;
  rsi: number | null;
  reason: string;
}

/**
 * 取引レコード（JSON内に格納）
 */
export interface TradeRecord {
  time: string;
  type: "buy" | "sell" | "short" | "cover";
  price: number;
  shares: number;
  totalAmount: number;
  profit?: number;
  profitRate?: number;
}

/**
 * アルゴリズム改善履歴
 * 失敗原因の蓄積と対策の適用を追跡する
 */
export const algorithmImprovements = mysqlTable("algorithm_improvements", {
  id: int("id").autoincrement().primaryKey(),
  /** 参照した日次レポートID */
  dailyReportId: int("dailyReportId").notNull(),
  /** 改善前のRSI上限 */
  prevRsiUpper: int("prevRsiUpper").notNull(),
  /** 改善前のRSI下限 */
  prevRsiLower: int("prevRsiLower").notNull(),
  /** 改善前の損切り率 */
  prevStopLossPercent: decimal("prevStopLossPercent", { precision: 5, scale: 2 }).notNull(),
  /** 改善後のRSI上限 */
  newRsiUpper: int("newRsiUpper").notNull(),
  /** 改善後のRSI下限 */
  newRsiLower: int("newRsiLower").notNull(),
  /** 改善後の損切り率 */
  newStopLossPercent: decimal("newStopLossPercent", { precision: 5, scale: 2 }).notNull(),
  /** 改善理由（AIによる分析） */
  improvementReason: text("improvementReason").notNull(),
  /** 適用日 */
  appliedAt: timestamp("appliedAt").defaultNow().notNull(),
});

export type AlgorithmImprovement = typeof algorithmImprovements.$inferSelect;
export type InsertAlgorithmImprovement = typeof algorithmImprovements.$inferInsert;

/**
 * 現在のアルゴリズムパラメータ設定（1レコードのみ）
 */
export const algorithmConfig = mysqlTable("algorithm_config", {
  id: int("id").autoincrement().primaryKey(),
  /** RSI買われすぎ閾値 */
  rsiUpper: int("rsiUpper").notNull().default(70),
  /** RSI売られすぎ閾値 */
  rsiLower: int("rsiLower").notNull().default(30),
  /** 損切り率（%） */
  stopLossPercent: decimal("stopLossPercent", { precision: 5, scale: 2 }).notNull().default("1.5"),
  /** 大口判定の基準出来高 */
  largeVolumeThreshold: int("largeVolumeThreshold").notNull().default(8000),
  /** 累計勝率（直近30日） */
  recentWinRate: decimal("recentWinRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 累計損益率（直近30日） */
  recentProfitRate: decimal("recentProfitRate", { precision: 10, scale: 6 }).notNull().default("0"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AlgorithmConfig = typeof algorithmConfig.$inferSelect;
export type InsertAlgorithmConfig = typeof algorithmConfig.$inferInsert;

/**
 * 仮想売買（ペーパートレード）記録
 * ユーザーがリアルタイムで「仮買い／仮売り」をボタンで記録するための個人取引履歴。
 * 実際の発注は行わない練習用途。
 */
export const paperTrades = mysqlTable("paper_trades", {
  id: int("id").autoincrement().primaryKey(),
  /** 取引したユーザーのID */
  userId: int("userId").notNull(),
  /** 銘柄コード（例: 9984） */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 銘柄名 */
  symbolName: varchar("symbolName", { length: 50 }).notNull(),
  /** ポジション方向: long=買い / short=空売り */
  side: mysqlEnum("side", ["long", "short"]).notNull(),
  /** エントリー価格（円） */
  entryPrice: decimal("entryPrice", { precision: 12, scale: 2 }).notNull(),
  /** 株数 */
  quantity: int("quantity").notNull(),
  /** ステータス: open=保有中 / closed=決済済み */
  status: mysqlEnum("status", ["open", "closed"]).notNull().default("open"),
  /** 決済価格（円）- 決済時のみ */
  exitPrice: decimal("exitPrice", { precision: 12, scale: 2 }),
  /** 損益額（円）- 決済時に計算 */
  pnl: bigint("pnl", { mode: "number" }),
  /** メモ（任意） */
  note: text("note"),
  /** エントリー時刻 */
  entryAt: timestamp("entryAt").defaultNow().notNull(),
  /** 決済時刻 */
  exitAt: timestamp("exitAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PaperTrade = typeof paperTrades.$inferSelect;
export type InsertPaperTrade = typeof paperTrades.$inferInsert;

/**
 * kabuステーション® プラン期限管理
 * Premiumプランの有効期限と継続条件の達成状況を管理する
 */
export const kabuPlanSettings = mysqlTable("kabu_plan_settings", {
  id: int("id").autoincrement().primaryKey(),
  /** 現在のプラン種別 */
  planType: mysqlEnum("planType", ["normal", "professional", "premium"]).notNull().default("professional"),
  /** プラン有効期限（YYYY-MM-DD） */
  planExpiresAt: varchar("planExpiresAt", { length: 10 }).notNull(),
  /** リマインドメール送信済みフラグ */
  reminderSent: boolean("reminderSent").notNull().default(false),
  /** リマインドメール送信日時 */
  reminderSentAt: timestamp("reminderSentAt"),
  /** メモ（継続条件の達成状況など） */
  note: text("note"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type KabuPlanSettings = typeof kabuPlanSettings.$inferSelect;
export type InsertKabuPlanSettings = typeof kabuPlanSettings.$inferInsert;

/**
 * リアルタイム受信1分足ローソク足ログ
 * Windowsスクリプトから送信された1分足OHLCVを記録する
 */
export const rtCandles = mysqlTable("rt_candles", {
  id: int("id").autoincrement().primaryKey(),
  /** 銘柄コード（例: 6976） */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull(),
  /** 1分足の時刻 (HH:MM) */
  candleTime: varchar("candleTime", { length: 5 }).notNull(),
  /** 始値（円） */
  open: decimal("open", { precision: 12, scale: 2 }).notNull(),
  /** 高値（円） */
  high: decimal("high", { precision: 12, scale: 2 }).notNull(),
  /** 低値（円） */
  low: decimal("low", { precision: 12, scale: 2 }).notNull(),
  /** 終値（円） */
  close: decimal("close", { precision: 12, scale: 2 }).notNull(),
  /** 出来高 */
  volume: bigint("volume", { mode: "number" }).notNull().default(0),
  /** 板情報スナップショット JSON（板圧力・大口注文・成行比率） */
  boardSnapshot: json("boardSnapshot").$type<BoardSnapshot | null>(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export interface BoardSnapshot {
  buyPressureRatio: number;   // 買い板合計 / 売り板合計
  largeBuyWall: boolean;      // 大口買い壁あり
  largeSellWall: boolean;     // 大口売り壁あり
  marketOrderRatio: number;   // 成行注文比率
  signal: "buy_pressure" | "sell_pressure" | "large_buy_wall" | "large_sell_wall" | "market_surge" | "neutral";
  // v5拡張フィールド（パターン6.14対応）
  largeAskWallRatio?: number;        // 売り板の最大注文 / 平均注文 の倍率
  largeBidWallRatio?: number;        // 買い板の最大注文 / 平均注文 の倍率
  largeAskWallPrice?: number | null; // 大口売り注文の価格
  largeBidWallPrice?: number | null; // 大口買い注文の価格
  nearAskWallPct?: number | null;    // 現値から大口売り注文までの距離（%）
  nearBidWallPct?: number | null;    // 現値から大口買い注文までの距離（%）
  marketOrderDirection?: "buy" | "sell" | "neutral"; // 成り行き注文の方向
  askCancelDetected?: boolean;       // 売り板の大口キャンセル検出
  bidCancelDetected?: boolean;       // 買い板の大口キャンセル検出
  icebergAskDetected?: boolean;      // 売りアイスバーグ注文検出
  icebergBidDetected?: boolean;      // 買いアイスバーグ注文検出
  totalAskQty?: number;              // 売り板合計数量
  totalBidQty?: number;              // 買い板合計数量
  // v8拡張: 10秒リングバッファ集約結果
  icebergAskCount?: number;          // 直近1分間のアイスバーグ検出回数（ask側）
  icebergBidCount?: number;          // 直近1分間のアイスバーグ検出回数（bid側）
  cancelAskCount?: number;           // 直近1分間のキャンセル検出回数（ask側）
  cancelBidCount?: number;           // 直近1分間のキャンセル検出回数（bid側）
  avgBprIn10s?: number;              // 直近1分間のBPR平均（10秒間隔集約）
  bprDeltaIn10s?: number;            // 直近1分間のBPR変化幅
  largeTradeDirection?: "buy" | "sell" | "neutral"; // 大口約定方向推定（10秒集約）
  boardSampleCount?: number;         // 集約サンプル数
}

export type RtCandle = typeof rtCandles.$inferSelect;
export type InsertRtCandle = typeof rtCandles.$inferInsert;

/**
 * リアルタイムシミュレーション取引ログ
 * 1分足受信時にシグナル判定して記録する架空取引
 */
export const rtTrades = mysqlTable("rt_trades", {
  id: int("id").autoincrement().primaryKey(),
  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull(),
  /** 銘柄コード */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 銘柄名 */
  symbolName: varchar("symbolName", { length: 50 }).notNull(),
  /** 取引種別: buy=買い / sell=売り / short=空売り / cover=買い戻し */
  action: mysqlEnum("action", ["buy", "sell", "short", "cover"]).notNull(),
  /** 約定価格（円） */
  price: decimal("price", { precision: 12, scale: 2 }).notNull(),
  /** 株数 */
  shares: int("shares").notNull(),
  /** 取引金額（円） */
  amount: bigint("amount", { mode: "number" }).notNull(),
  /** 損益額（決済時のみ、円） */
  pnl: bigint("pnl", { mode: "number" }),
  /** シグナル理由 */
  reason: text("reason").notNull(),
  /** エントリー/決済時刻 (HH:MM) */
  tradeTime: varchar("tradeTime", { length: 5 }).notNull(),
  /** ポジション方向: long / short */
  side: mysqlEnum("side", ["long", "short"]).notNull(),
  /** 板情報シグナル（あれば） */
  boardSignal: varchar("boardSignal", { length: 30 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type RtTrade = typeof rtTrades.$inferSelect;
export type InsertRtTrade = typeof rtTrades.$inferInsert;

/**
 * リアルタイムシミュレーション日次サマリー
 * 大引け後に集計して保存する当日の成績
 */
export const rtDailySummaries = mysqlTable("rt_daily_summaries", {
  id: int("id").autoincrement().primaryKey(),
  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull().unique(),
  /** 元金（円） */
  initialCapital: bigint("initialCapital", { mode: "number" }).notNull(),
  /** 当日損益合計（円） */
  totalPnl: bigint("totalPnl", { mode: "number" }).notNull().default(0),
  /** 取引回数 */
  tradesCount: int("tradesCount").notNull().default(0),
  /** 勝ちトレード数 */
  winCount: int("winCount").notNull().default(0),
  /** 負けトレード数 */
  lossCount: int("lossCount").notNull().default(0),
  /** 受信した1分足本数 */
  candlesReceived: int("candlesReceived").notNull().default(0),
  /** レポートメール送信済みフラグ */
  reportSent: boolean("reportSent").notNull().default(false),
  /** レポートメール送信日時 */
  reportSentAt: timestamp("reportSentAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type RtDailySummary = typeof rtDailySummaries.$inferSelect;
export type InsertRtDailySummary = typeof rtDailySummaries.$inferInsert;

/**
 * 自動売買: 発注指示テーブル
 * クラウド（orderBridge）がrt_tradesの新規エントリー/決済を検知して生成し、
 * ローカルPC（kabu_order_executor.py）がポーリングして実行する。
 *
 * ライフサイクル:
 *   pending → sent → executed/failed
 *   pending → expired (60秒超過、entryのみ)
 *   pending → cancelled (緊急停止時)
 */
export const orderInstructions = mysqlTable("order_instructions", {
  id: int("id").autoincrement().primaryKey(),

  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull(),

  /** 銘柄コード（例: 9984） */
  symbol: varchar("symbol", { length: 10 }).notNull(),

  /** 銘柄名 */
  symbolName: varchar("symbolName", { length: 50 }).notNull(),

  /**
   * 売買方向
   * buy: 信用新規買い (Side="2", CashMargin=2)
   * sell: 信用返済売り (Side="1", CashMargin=3) — LONG決済
   * short: 信用新規売り (Side="1", CashMargin=2)
   * cover: 信用返済買い (Side="2", CashMargin=3) — SHORT決済
   */
  side: mysqlEnum("oi_side", ["buy", "sell", "short", "cover"]).notNull(),

  /**
   * 指示種別
   * entry: 新規建て（60秒で期限切れ）
   * exit: 決済（期限なし、必ず実行）
   * force_close: 大引け強制決済（期限なし、必ず実行）
   */
  instructionType: mysqlEnum("oi_instruction_type", ["entry", "exit", "force_close"]).notNull(),

  /** 注文数量（株） */
  qty: int("qty").notNull().default(100),

  /**
   * ステータス
   * pending: 未実行（executorがポーリングで取得する対象）
   * sent: KABU APIに送信済み（約定待ち）
   * executed: 約定完了
   * failed: 発注失敗（APIエラー等）
   * expired: 期限切れ（entryのみ、60秒超過）
   * cancelled: 緊急停止等でキャンセル
   */
  status: mysqlEnum("oi_status", ["pending", "sent", "executed", "failed", "expired", "cancelled"]).notNull().default("pending"),

  /** シグナル理由（realtimeSimEngineのreason） */
  reason: text("reason").notNull(),

  /** 参照価格（シグナル発生時の価格、実際の約定価格ではない） */
  referencePrice: decimal("referencePrice", { precision: 12, scale: 2 }).notNull(),

  /** 期限切れ日時（entryのみ: createdAt + 60秒、exit/force_closeはnull） */
  expiresAt: timestamp("expiresAt"),

  /** KABU Station APIから返されたOrderId */
  kabuOrderId: varchar("kabuOrderId", { length: 30 }),

  /** 実約定価格（約定確認後に記録） */
  executedPrice: decimal("executedPrice", { precision: 12, scale: 2 }),

  /** 約定日時 */
  executedAt: timestamp("executedAt"),

  /** 損益（決済時のみ、円） */
  pnl: bigint("pnl", { mode: "number" }),

  /** 対応するrt_tradesのID（FK参照用、外部キー制約なし） */
  rtTradeId: int("rtTradeId"),

  /** エラーメッセージ（failed時） */
  errorMessage: text("errorMessage"),

  /** ドライランモードで生成されたか */
  isDryRun: boolean("isDryRun").notNull().default(true),

  /** executor側のログ（JSON形式、デバッグ用） */
  executorLog: json("executorLog").$type<Record<string, unknown> | null>(),

  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type OrderInstruction = typeof orderInstructions.$inferSelect;
export type InsertOrderInstruction = typeof orderInstructions.$inferInsert;

/**
 * 自動売買: 日次リスク管理テーブル
 * 1日1レコード。日次の損益上限・緊急停止状態を管理する。
 */
export const autoTradeDaily = mysqlTable("auto_trade_daily", {
  id: int("id").autoincrement().primaryKey(),

  /** 対象日 (YYYY-MM-DD) */
  tradeDate: varchar("tradeDate", { length: 10 }).notNull().unique(),

  /** 当日の実現損益合計（円） */
  realizedPnl: bigint("realizedPnl", { mode: "number" }).notNull().default(0),

  /** 当日の取引回数 */
  tradeCount: int("tradeCount").notNull().default(0),

  /** 日次損失上限（円、負の値）- これを超えたら新規エントリー停止 */
  dailyLossLimit: bigint("dailyLossLimit", { mode: "number" }).notNull().default(-100000),

  /** 取引有効フラグ（falseで全発注停止） */
  tradingEnabled: boolean("tradingEnabled").notNull().default(true),

  /** 緊急停止フラグ（手動またはリスク管理で停止） */
  emergencyStop: boolean("emergencyStop").notNull().default(false),

  /** 緊急停止理由 */
  emergencyStopReason: text("emergencyStopReason"),

  /** ドライランモード（true=実際の発注を行わない） */
  isDryRun: boolean("isDryRun").notNull().default(true),

  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AutoTradeDaily = typeof autoTradeDaily.$inferSelect;
export type InsertAutoTradeDaily = typeof autoTradeDaily.$inferInsert;
