import {
  bigint,
  boolean,
  decimal,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * デイリーシミュレーションレポート（1日1レコード）
 * 毎平日の架空トレーディング結果を保存する
 */
export const dailyReports = mysqlTable("daily_reports", {
  id: int("id").autoincrement().primaryKey(),
  /** 対象日 (YYYY-MM-DD) */
  reportDate: varchar("reportDate", { length: 10 }).notNull().unique(),
  /** 総元金（円） */
  totalInitialCapital: bigint("totalInitialCapital", { mode: "number" }).notNull(),
  /** 検証後評価額合計（円） */
  totalFinalBalance: bigint("totalFinalBalance", { mode: "number" }).notNull(),
  /** 総合損益額（円） */
  totalProfitAmount: bigint("totalProfitAmount", { mode: "number" }).notNull(),
  /** 総合利益率（小数） */
  totalProfitRate: decimal("totalProfitRate", { precision: 10, scale: 6 }).notNull(),
  /** 全銘柄の勝ちトレード数 */
  totalWinCount: int("totalWinCount").notNull().default(0),
  /** 全銘柄の負けトレード数 */
  totalLossCount: int("totalLossCount").notNull().default(0),
  /** 全体勝率（小数） */
  overallWinRate: decimal("overallWinRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 使用したRSI上限パラメータ */
  rsiUpper: int("rsiUpper").notNull().default(70),
  /** 使用したRSI下限パラメータ */
  rsiLower: int("rsiLower").notNull().default(30),
  /** 使用した損切り率（%） */
  stopLossPercent: decimal("stopLossPercent", { precision: 5, scale: 2 }).notNull().default("1.5"),
  /** AIによる総合分析コメント */
  aiSummary: text("aiSummary"),
  /** スケジューラーによる自動生成かどうか */
  isAutoGenerated: boolean("isAutoGenerated").notNull().default(false),
  /** スケジュールタスクUID */
  scheduleCronTaskUid: varchar("scheduleCronTaskUid", { length: 65 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type DailyReport = typeof dailyReports.$inferSelect;
export type InsertDailyReport = typeof dailyReports.$inferInsert;

/**
 * 銘柄別シミュレーション結果（1日×10銘柄 = 10レコード）
 */
export const stockReports = mysqlTable("stock_reports", {
  id: int("id").autoincrement().primaryKey(),
  /** 親レポートID */
  dailyReportId: int("dailyReportId").notNull(),
  /** 銘柄コード */
  symbol: varchar("symbol", { length: 10 }).notNull(),
  /** 銘柄名 */
  name: varchar("name", { length: 50 }).notNull(),
  /** 元金（円） */
  initialCapital: bigint("initialCapital", { mode: "number" }).notNull(),
  /** 最終評価額（円） */
  finalBalance: bigint("finalBalance", { mode: "number" }).notNull(),
  /** 損益額（円） */
  profitAmount: bigint("profitAmount", { mode: "number" }).notNull(),
  /** 利益率（小数） */
  profitRate: decimal("profitRate", { precision: 10, scale: 6 }).notNull(),
  /** 総取引回数 */
  tradesCount: int("tradesCount").notNull().default(0),
  /** 勝ちトレード数 */
  winCount: int("winCount").notNull().default(0),
  /** 勝率（小数） */
  winRate: decimal("winRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 取引履歴 JSON */
  trades: json("trades").notNull().$type<TradeRecord[]>(),
  /** 損失原因リスト JSON */
  lossCauses: json("lossCauses").notNull().$type<string[]>(),
  /** 対策リスト JSON */
  countermeasures: json("countermeasures").notNull().$type<string[]>(),
  /** シグナル一覧 JSON - 買い/売りタイミング・理由の詳細 */
  signals: json("signals").$type<SignalRecord[]>(),
  /** 実データ使用フラグ */
  isRealData: boolean("isRealData").notNull().default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type StockReport = typeof stockReports.$inferSelect;
export type InsertStockReport = typeof stockReports.$inferInsert;

/**
 * シグナルレコード（JSON内に格納） - 実際のチャートと同様の買い/売りタイミング詳細
 */
export interface SignalRecord {
  time: string;
  type: "buy" | "sell" | "warn";
  price: number;
  ma5: number | null;
  ma25: number | null;
  rsi: number | null;
  reason: string;
}

/**
 * 取引レコード（JSON内に格納）
 */
export interface TradeRecord {
  time: string;
  type: "buy" | "sell";
  price: number;
  shares: number;
  totalAmount: number;
  profit?: number;
  profitRate?: number;
}

/**
 * アルゴリズム改善履歴
 * 失敗原因の蓄積と対策の適用を追跡する
 */
export const algorithmImprovements = mysqlTable("algorithm_improvements", {
  id: int("id").autoincrement().primaryKey(),
  /** 参照した日次レポートID */
  dailyReportId: int("dailyReportId").notNull(),
  /** 改善前のRSI上限 */
  prevRsiUpper: int("prevRsiUpper").notNull(),
  /** 改善前のRSI下限 */
  prevRsiLower: int("prevRsiLower").notNull(),
  /** 改善前の損切り率 */
  prevStopLossPercent: decimal("prevStopLossPercent", { precision: 5, scale: 2 }).notNull(),
  /** 改善後のRSI上限 */
  newRsiUpper: int("newRsiUpper").notNull(),
  /** 改善後のRSI下限 */
  newRsiLower: int("newRsiLower").notNull(),
  /** 改善後の損切り率 */
  newStopLossPercent: decimal("newStopLossPercent", { precision: 5, scale: 2 }).notNull(),
  /** 改善理由（AIによる分析） */
  improvementReason: text("improvementReason").notNull(),
  /** 適用日 */
  appliedAt: timestamp("appliedAt").defaultNow().notNull(),
});

export type AlgorithmImprovement = typeof algorithmImprovements.$inferSelect;
export type InsertAlgorithmImprovement = typeof algorithmImprovements.$inferInsert;

/**
 * 現在のアルゴリズムパラメータ設定（1レコードのみ）
 */
export const algorithmConfig = mysqlTable("algorithm_config", {
  id: int("id").autoincrement().primaryKey(),
  /** RSI買われすぎ閾値 */
  rsiUpper: int("rsiUpper").notNull().default(70),
  /** RSI売られすぎ閾値 */
  rsiLower: int("rsiLower").notNull().default(30),
  /** 損切り率（%） */
  stopLossPercent: decimal("stopLossPercent", { precision: 5, scale: 2 }).notNull().default("1.5"),
  /** 大口判定の基準出来高 */
  largeVolumeThreshold: int("largeVolumeThreshold").notNull().default(8000),
  /** 累計勝率（直近30日） */
  recentWinRate: decimal("recentWinRate", { precision: 10, scale: 6 }).notNull().default("0"),
  /** 累計損益率（直近30日） */
  recentProfitRate: decimal("recentProfitRate", { precision: 10, scale: 6 }).notNull().default("0"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AlgorithmConfig = typeof algorithmConfig.$inferSelect;
export type InsertAlgorithmConfig = typeof algorithmConfig.$inferInsert;
