/**
 * 本日のシミュレーションをDBに保存するスクリプト
 * 実行: npx tsx server/runTodaySimulation.ts
 */
import { generateRealDailyReport } from "./realSimulation";
import { saveDailyReport, getAlgorithmConfig } from "./db";
import { invokeLLM } from "./_core/llm";

async function main() {
  const today = new Date();
  const dateStr = today.toISOString().slice(0, 10);

  console.log(`=== 本日(${dateStr})の実データシミュレーション実行 ===`);

  const config = await getAlgorithmConfig();
  const rsiUpper = config?.rsiUpper ?? 70;
  const rsiLower = config?.rsiLower ?? 30;
  const stopLossPercent = parseFloat(String(config?.stopLossPercent ?? "1.5"));

  console.log(`パラメータ: RSI上限=${rsiUpper} RSI下限=${rsiLower} 損切り=${stopLossPercent}%`);

  const simResult = await generateRealDailyReport(dateStr, rsiUpper, rsiLower, stopLossPercent);

  const dataSource = simResult.isRealData
    ? `実際の株価データ (${simResult.realDataCount}/10銘柄)`
    : "架空データ（市場データ取得失敗のためフォールバック）";

  console.log(`\nデータソース: ${dataSource}`);
  console.log(`総合損益: ${simResult.totalProfitAmount.toLocaleString()}円`);
  console.log(`全体勝率: ${(simResult.overallWinRate * 100).toFixed(1)}%`);

  // AI分析サマリーの生成
  let aiSummary: string | undefined;
  try {
    const lossStocks = simResult.stockReports
      .filter((r) => r.profitAmount < 0)
      .map((r) => `${r.name}(${r.symbol}): ${r.profitAmount.toLocaleString()}円, 勝率${(r.winRate * 100).toFixed(0)}%`)
      .join(", ");

    const winStocks = simResult.stockReports
      .filter((r) => r.profitAmount >= 0)
      .map((r) => `${r.name}(${r.symbol}): +${r.profitAmount.toLocaleString()}円`)
      .join(", ");

    const prompt = `あなたは株式デイトレードのAIアドバイザーです。
以下の${dateStr}の実際の株価データを使ったシミュレーション結果を分析し、改善提案を日本語で200文字以内で簡潔にまとめてください。

【本日の結果】（${dataSource}）
- 総合損益: ${simResult.totalProfitAmount.toLocaleString()}円 (${(simResult.totalProfitRate * 100).toFixed(2)}%)
- 全体勝率: ${(simResult.overallWinRate * 100).toFixed(1)}%
- 使用パラメータ: RSI上限${rsiUpper} / RSI下限${rsiLower} / 損切り${stopLossPercent}%
- 利益銘柄: ${winStocks || "なし"}
- 損失銘柄: ${lossStocks || "なし"}

改善提案（200文字以内）:`;

    const response = await invokeLLM({
      messages: [{ role: "user", content: prompt }],
    });
    const rawContent = response.choices[0]?.message?.content;
    aiSummary = typeof rawContent === "string" ? rawContent : undefined;
    console.log(`\nAI分析: ${aiSummary}`);
  } catch (e) {
    console.warn("AI summary generation failed:", e);
  }

  // DBに保存
  const savedReport = await saveDailyReport(
    {
      reportDate: simResult.date,
      totalInitialCapital: simResult.totalInitialCapital,
      totalFinalBalance: simResult.totalFinalBalance,
      totalProfitAmount: simResult.totalProfitAmount,
      totalProfitRate: simResult.totalProfitRate.toString(),
      totalWinCount: simResult.totalWinCount,
      totalLossCount: simResult.totalLossCount,
      overallWinRate: simResult.overallWinRate.toString(),
      rsiUpper,
      rsiLower,
      stopLossPercent: stopLossPercent.toString(),
      aiSummary: aiSummary
        ? `[${dataSource}]\n${aiSummary}`
        : `[${dataSource}]`,
      isAutoGenerated: true,
    },
    simResult.stockReports.map((r) => ({
      symbol: r.symbol,
      name: r.name,
      initialCapital: r.initialCapital,
      finalBalance: r.finalBalance,
      profitAmount: r.profitAmount,
      profitRate: r.profitRate.toString(),
      tradesCount: r.tradesCount,
      winCount: r.winCount,
      winRate: r.winRate.toString(),
      trades: r.trades,
      lossCauses: r.lossCauses,
      countermeasures: r.countermeasures,
      signals: r.signals ?? [],
      isRealData: r.isRealData ?? false,
    }))
  );

  console.log(`\n✅ DBに保存完了 (ID: ${savedReport.id})`);
  console.log("レポート履歴ページで確認できます。");
}

main().catch(console.error);
