/**
 * スケジュール実行ハンドラー
 * 毎平日 JST 8:00（UTC 23:00 前日）に自動でシミュレーションを実行してレポートを保存する
 * ★ 実際のJ-Quantsデータを使用（前営業日分を取得）
 */
import type { Request, Response } from "express";
import { sdk } from "./_core/sdk";
import {
  getAlgorithmConfig,
  saveDailyReport,
  updateAlgorithmConfig,
  saveAlgorithmImprovement,
  getRecentStats,
} from "./db";
import { generateRealDailyReport } from "./realSimulation";
import { invokeLLM } from "./_core/llm";
import { notifyOwner } from "./_core/notification";

/**
 * 前営業日（土日祈日を除く直近の平日）を UTC 日付で返す
 * JST 8:00（UTC 23:00 前日）に実行されるため、「実行時刻の前日」が前営業日になる
 */
function getPreviousBusinessDay(): Date {
  // UTC 23:00 前日 = JST 8:00 当日なので、「実行時刻の前日」 = 前営業日
  const now = new Date();
  // UTC で小数点以下を切り捨てて前日に戻る
  const yesterday = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() - 1));
  const dow = yesterday.getUTCDay(); // 0=日, 6=土
  if (dow === 0) {
    // 日曜なら金曜に戻る
    yesterday.setUTCDate(yesterday.getUTCDate() - 2);
  } else if (dow === 6) {
    // 土曜なら金曜に戻る
    yesterday.setUTCDate(yesterday.getUTCDate() - 1);
  }
  return yesterday;
}

/**
 * 毎平日のシミュレーション実行ハンドラー
 * POST /api/scheduled/daily-simulation
 */
export async function dailySimulationHandler(req: Request, res: Response) {
  try {
    // Heartbeat認証
    const user = await sdk.authenticateRequest(req);
    if (!user.isCron) {
      return res.status(403).json({ error: "cron-only endpoint" });
    }

    // JST 8:00（UTC 23:00 前日）に実行されるため、「前営業日」のデータを取得する
    // J-Quants の1分足は当日中には確定しないため、前営業日分を対象とする
    const targetDate = getPreviousBusinessDay();
    const dateStr = targetDate.toISOString().slice(0, 10);
    console.log(`[daily-simulation] Running REAL DATA simulation for previous business day: ${dateStr}`);

    // 現在のアルゴリズム設定を取得
    const config = await getAlgorithmConfig();
    const rsiUpper = config?.rsiUpper ?? 70;
    const rsiLower = config?.rsiLower ?? 30;
    const stopLossPercent = parseFloat(String(config?.stopLossPercent ?? "1.5"));

    // ★ 実際のYahoo Financeデータを使ったシミュレーション実行
    console.log(`[daily-simulation] Fetching real J-Quants data for ${dateStr}...`);
    const simResult = await generateRealDailyReport(dateStr, rsiUpper, rsiLower, stopLossPercent);

    const dataSource = simResult.isRealData
      ? `実際の株価データ (${simResult.realDataCount}銘柄)`
      : "架空データ（市場データ取得失敗のためフォールバック）";

    console.log(`[daily-simulation] Data source: ${dataSource}`);
    console.log(`[daily-simulation] Real data: ${simResult.realDataCount} stocks, isRealData=${simResult.isRealData}`);

    // 実データが1銘柄も取得できなかった場合は警告ログを出す
    if (!simResult.isRealData) {
      console.error(`[daily-simulation] WARNING: All stocks fell back to simulated data! Check Yahoo Finance API.`);
    }

    // AI分析サマリーの生成
    let aiSummary: string | undefined;
    try {
      const lossStocks = simResult.stockReports
        .filter((r) => r.profitAmount < 0)
        .map(
          (r) =>
            `${r.name}(${r.symbol}): ${r.profitAmount.toLocaleString()}円, 勝率${(r.winRate * 100).toFixed(0)}%`
        )
        .join(", ");

      const winStocks = simResult.stockReports
        .filter((r) => r.profitAmount >= 0)
        .map((r) => `${r.name}(${r.symbol}): +${r.profitAmount.toLocaleString()}円`)
        .join(", ");

      const prompt = `あなたは株式デイトレードのAIアドバイザーです。
以下の${dateStr}の実際の株価データを使ったシミュレーション結果を分析し、改善提案を日本語で200文字以内で簡潔にまとめてください。

【本日の結果】（${dataSource}）
- 総合損益: ${simResult.totalProfitAmount.toLocaleString()}円 (${(simResult.totalProfitRate * 100).toFixed(2)}%)
- 全体勝率: ${(simResult.overallWinRate * 100).toFixed(1)}%
- 使用パラメータ: RSI上限${rsiUpper} / RSI下限${rsiLower} / 損切り${stopLossPercent}%
- 利益銘柄: ${winStocks || "なし"}
- 損失銘柄: ${lossStocks || "なし"}

改善提案（200文字以内）:`;

      const response = await invokeLLM({
        messages: [{ role: "user", content: prompt }],
      });
      const rawContent = response.choices[0]?.message?.content;
      aiSummary = typeof rawContent === "string" ? rawContent : undefined;
    } catch (e) {
      console.warn("[daily-simulation] AI summary generation failed:", e);
    }

    // データベースに保存
    const savedReport = await saveDailyReport(
      {
        reportDate: simResult.date,
        totalInitialCapital: simResult.totalInitialCapital,
        totalFinalBalance: simResult.totalFinalBalance,
        totalProfitAmount: simResult.totalProfitAmount,
        totalProfitRate: simResult.totalProfitRate.toString(),
        totalWinCount: simResult.totalWinCount,
        totalLossCount: simResult.totalLossCount,
        overallWinRate: simResult.overallWinRate.toString(),
        rsiUpper,
        rsiLower,
        stopLossPercent: stopLossPercent.toString(),
        aiSummary: aiSummary
          ? `[${dataSource}]\n${aiSummary}`
          : `[${dataSource}]`,
        isAutoGenerated: true,
      },
      simResult.stockReports.map((r) => ({
        symbol: r.symbol,
        name: r.name,
        initialCapital: r.initialCapital,
        finalBalance: r.finalBalance,
        profitAmount: r.profitAmount,
        profitRate: r.profitRate.toString(),
        tradesCount: r.tradesCount,
        winCount: r.winCount,
        winRate: r.winRate.toString(),
        trades: r.trades,
        lossCauses: r.lossCauses,
        countermeasures: r.countermeasures,
        signals: r.signals ?? [],
        isRealData: r.isRealData ?? false,
      }))
    );

    // AIによるアルゴリズム自動改善（週に1回程度、金曜日に実行）
    // targetDateは前営業日なので、金曜日（UTCで判定）なら実行
    if (targetDate.getUTCDay() === 5) {
      try {
        console.log("[daily-simulation] Running weekly algorithm improvement (Friday)");
        const stats = await getRecentStats(7);

        const prompt = `あなたは株式デイトレードのアルゴリズム最適化AIです。
直近7日間の実際の株価データを使ったシミュレーション結果を分析し、パラメータ改善案をJSON形式で返してください。

【現在のパラメータ】
- RSI上限: ${rsiUpper}
- RSI下限: ${rsiLower}
- 損切り率: ${stopLossPercent}%

【直近7日間の成績】
- 平均勝率: ${(stats.avgWinRate * 100).toFixed(1)}%
- 平均損益率: ${(stats.avgProfitRate * 100).toFixed(2)}%

目標勝率は80〜90%です。

以下のJSON形式で回答してください:
{
  "newRsiUpper": <数値 55-90>,
  "newRsiLower": <数値 10-45>,
  "newStopLossPercent": <数値 0.5-5.0>,
  "reason": "<改善理由を100文字以内で>"
}`;

        const response = await invokeLLM({
          messages: [{ role: "user", content: prompt }],
          response_format: {
            type: "json_schema",
            json_schema: {
              name: "algorithm_improvement",
              strict: true,
              schema: {
                type: "object",
                properties: {
                  newRsiUpper: { type: "number" },
                  newRsiLower: { type: "number" },
                  newStopLossPercent: { type: "number" },
                  reason: { type: "string" },
                },
                required: ["newRsiUpper", "newRsiLower", "newStopLossPercent", "reason"],
                additionalProperties: false,
              },
            },
          },
        });

        const rawContent = response.choices[0]?.message?.content;
        const content = typeof rawContent === "string" ? rawContent : null;
        if (content) {
          const parsed = JSON.parse(content);
          const newParams = {
            newRsiUpper: Math.min(90, Math.max(55, parsed.newRsiUpper)),
            newRsiLower: Math.min(45, Math.max(10, parsed.newRsiLower)),
            newStopLossPercent: Math.min(5.0, Math.max(0.5, parsed.newStopLossPercent)),
            reason: parsed.reason,
          };

          await saveAlgorithmImprovement({
            dailyReportId: savedReport.id,
            prevRsiUpper: rsiUpper,
            prevRsiLower: rsiLower,
            prevStopLossPercent: String(stopLossPercent),
            newRsiUpper: newParams.newRsiUpper,
            newRsiLower: newParams.newRsiLower,
            newStopLossPercent: String(newParams.newStopLossPercent),
            improvementReason: newParams.reason,
          });

          await updateAlgorithmConfig({
            rsiUpper: newParams.newRsiUpper,
            rsiLower: newParams.newRsiLower,
            stopLossPercent: String(newParams.newStopLossPercent),
          });

          console.log("[daily-simulation] Algorithm improved:", newParams.reason);
        }
      } catch (e) {
        console.warn("[daily-simulation] Weekly algorithm improvement failed:", e);
      }
    }

    // オーナーへの通知
    const profitStr =
      simResult.totalProfitAmount >= 0
        ? `+${simResult.totalProfitAmount.toLocaleString()}円`
        : `${simResult.totalProfitAmount.toLocaleString()}円`;
    const winRateStr = `${(simResult.overallWinRate * 100).toFixed(1)}%`;

    await notifyOwner({
      title: `📊 ${dateStr} デイリーシミュレーション完了（実データ）`,
      content: `本日の結果: 損益 ${profitStr} | 勝率 ${winRateStr} | ${dataSource}\n${aiSummary ?? ""}`,
    });

    console.log(
      `[daily-simulation] Completed for ${dateStr}: profit=${simResult.totalProfitAmount}, winRate=${simResult.overallWinRate}`
    );

    return res.json({
      ok: true,
      date: dateStr,
      profitAmount: simResult.totalProfitAmount,
      winRate: simResult.overallWinRate,
      dataSource,
    });
  } catch (error) {
    console.error("[daily-simulation] Handler error:", error);
    return res.status(500).json({
      error: String(error),
      stack: error instanceof Error ? error.stack : undefined,
      context: { url: req.url, taskUid: "unknown" },
      timestamp: new Date().toISOString(),
    });
  }
}

/**
 * オーナー専用の手動シミュレーション実行ハンドラー
 * POST /api/admin/manual-simulation
 * ヘッダー: x-owner-key: <BUILT_IN_FORGE_API_KEY>
 */
export async function manualSimulationHandler(req: Request, res: Response) {
  // オーナーAPIキー認証
  const ownerKey = req.headers["x-owner-key"];
  const expectedKey = process.env.BUILT_IN_FORGE_API_KEY;
  if (!ownerKey || ownerKey !== expectedKey) {
    return res.status(403).json({ error: "Unauthorized: invalid owner key" });
  }

  try {
    const today = new Date();
    const dateStr = today.toISOString().slice(0, 10);
    console.log(`[manual-simulation] Running REAL DATA simulation for ${dateStr}`);

    // 現在のアルゴリズム設定を取得
    const config = await getAlgorithmConfig();
    const rsiUpper = config?.rsiUpper ?? 70;
    const rsiLower = config?.rsiLower ?? 30;
    const stopLossPercent = parseFloat(String(config?.stopLossPercent ?? "1.5"));

    // ★ 実際のYahoo Financeデータを使ったシミュレーション実行
    console.log(`[manual-simulation] Fetching real Yahoo Finance data for ${dateStr}...`);
    const simResult = await generateRealDailyReport(dateStr, rsiUpper, rsiLower, stopLossPercent);

    const dataSource = `実際の株価データ (${simResult.realDataCount}銘柄)`;
    console.log(`[manual-simulation] Data source: ${dataSource}`);

    // AI分析サマリーの生成
    let aiSummary: string | undefined;
    try {
      const lossStocks = simResult.stockReports
        .filter((r) => r.profitAmount < 0)
        .map(
          (r) =>
            `${r.name}(${r.symbol}): ${r.profitAmount.toLocaleString()}円, 勝率${(r.winRate * 100).toFixed(0)}%`
        )
        .join(", ");

      const winStocks = simResult.stockReports
        .filter((r) => r.profitAmount >= 0)
        .map((r) => `${r.name}(${r.symbol}): +${r.profitAmount.toLocaleString()}円`)
        .join(", ");

      const prompt = `あなたは株式デイトレードのAIアドバイザーです。
以下の${dateStr}の実際の株価データを使ったシミュレーション結果を分析し、改善提案を日本語で200文字以内で簡潔にまとめてください。

【本日の結果】（${dataSource}）
- 総合損益: ${simResult.totalProfitAmount.toLocaleString()}円 (${(simResult.totalProfitRate * 100).toFixed(2)}%)
- 全体勝率: ${(simResult.overallWinRate * 100).toFixed(1)}%
- 使用パラメータ: RSI上限${rsiUpper} / RSI下限${rsiLower} / 損切り${stopLossPercent}%
- 利益銘柄: ${winStocks || "なし"}
- 損失銘柄: ${lossStocks || "なし"}

改善提案（200文字以内）:`;

      const response = await invokeLLM({
        messages: [{ role: "user", content: prompt }],
      });
      const rawContent = response.choices[0]?.message?.content;
      aiSummary = typeof rawContent === "string" ? rawContent : undefined;
    } catch (e) {
      console.warn("[manual-simulation] AI summary generation failed:", e);
    }

    // データベースに保存（べき等: 同じ日付で再実行すると上書き）
    const savedReport = await saveDailyReport(
      {
        reportDate: simResult.date,
        totalInitialCapital: simResult.totalInitialCapital,
        totalFinalBalance: simResult.totalFinalBalance,
        totalProfitAmount: simResult.totalProfitAmount,
        totalProfitRate: simResult.totalProfitRate.toString(),
        totalWinCount: simResult.totalWinCount,
        totalLossCount: simResult.totalLossCount,
        overallWinRate: simResult.overallWinRate.toString(),
        rsiUpper,
        rsiLower,
        stopLossPercent: stopLossPercent.toString(),
        aiSummary: aiSummary
          ? `[${dataSource}]\n${aiSummary}`
          : `[${dataSource}]`,
        isAutoGenerated: false,
      },
      simResult.stockReports.map((r) => ({
        symbol: r.symbol,
        name: r.name,
        initialCapital: r.initialCapital,
        finalBalance: r.finalBalance,
        profitAmount: r.profitAmount,
        profitRate: r.profitRate.toString(),
        tradesCount: r.tradesCount,
        winCount: r.winCount,
        winRate: r.winRate.toString(),
        trades: r.trades,
        lossCauses: r.lossCauses,
        countermeasures: r.countermeasures,
        signals: r.signals ?? [],
        isRealData: r.isRealData ?? false,
      }))
    );

    // オーナーへの通知
    const profitStr =
      simResult.totalProfitAmount >= 0
        ? `+${simResult.totalProfitAmount.toLocaleString()}円`
        : `${simResult.totalProfitAmount.toLocaleString()}円`;
    const winRateStr = `${(simResult.overallWinRate * 100).toFixed(1)}%`;

    await notifyOwner({
      title: `📊 ${dateStr} 手動シミュレーション完了（実データ）`,
      content: `本日の結果: 損益 ${profitStr} | 勝率 ${winRateStr} | ${dataSource}\n${aiSummary ?? ""}`,
    });

    console.log(
      `[manual-simulation] Completed for ${dateStr}: profit=${simResult.totalProfitAmount}, winRate=${simResult.overallWinRate}`
    );

    return res.json({
      ok: true,
      date: dateStr,
      profitAmount: simResult.totalProfitAmount,
      winRate: simResult.overallWinRate,
      dataSource,
      stockReports: simResult.stockReports.map((r) => ({
        symbol: r.symbol,
        name: r.name,
        profitAmount: r.profitAmount,
        profitRate: r.profitRate,
        winRate: r.winRate,
        tradesCount: r.tradesCount,
        winCount: r.winCount,
        lossCount: r.lossCount,
        isRealData: r.isRealData,
      })),
      aiSummary,
      reportId: savedReport.id,
    });
  } catch (error) {
    console.error("[manual-simulation] Handler error:", error);
    return res.status(500).json({
      error: String(error),
      stack: error instanceof Error ? error.stack : undefined,
      timestamp: new Date().toISOString(),
    });
  }
}
