/**
 * スケジュール実行ハンドラー
 * 毎平日 JST 8:00（UTC 23:00 前日）に自動でシミュレーションを実行してレポートを保存する
 * ★ 実際のJ-Quantsデータを使用（前営業日分を取得）
 */
import type { Request, Response } from "express";
import { sdk } from "./_core/sdk";
import {
  getAlgorithmConfig,
  saveDailyReport,
  updateAlgorithmConfig,
  saveAlgorithmImprovement,
  getRecentStats,
  getDb,
} from "./db";
import { generateRealDailyReport } from "./realSimulation";
import { invokeLLM } from "./_core/llm";
import { notifyOwner } from "./_core/notification";

/**
 * 前営業日（土日祈日を除く直近の平日）を UTC 日付で返す
 * JST 8:00（UTC 23:00 前日）に実行されるため、「実行時刻の前日」が前営業日になる
 */
function getPreviousBusinessDay(): Date {
  // UTC 23:00 前日 = JST 8:00 当日なので、「実行時刻の前日」 = 前営業日
  const now = new Date();
  // UTC で小数点以下を切り捨てて前日に戻る
  const yesterday = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() - 1));
  const dow = yesterday.getUTCDay(); // 0=日, 6=土
  if (dow === 0) {
    // 日曜なら金曜に戻る
    yesterday.setUTCDate(yesterday.getUTCDate() - 2);
  } else if (dow === 6) {
    // 土曜なら金曜に戻る
    yesterday.setUTCDate(yesterday.getUTCDate() - 1);
  }
  return yesterday;
}

/**
 * 毎平日のシミュレーション実行ハンドラー
 * POST /api/scheduled/daily-simulation
 */
export async function dailySimulationHandler(req: Request, res: Response) {
  try {
    // Heartbeat認証
    const user = await sdk.authenticateRequest(req);
    if (!user.isCron) {
      return res.status(403).json({ error: "cron-only endpoint" });
    }

    // JST 8:00（UTC 23:00 前日）に実行されるため、「前営業日」のデータを取得する
    // J-Quants の1分足は当日中には確定しないため、前営業日分を対象とする
    const targetDate = getPreviousBusinessDay();
    const dateStr = targetDate.toISOString().slice(0, 10);
    console.log(`[daily-simulation] Running REAL DATA simulation for previous business day: ${dateStr}`);

    // 現在のアルゴリズム設定を取得
    const config = await getAlgorithmConfig();
    const rsiUpper = config?.rsiUpper ?? 70;
    const rsiLower = config?.rsiLower ?? 30;
    const stopLossPercent = parseFloat(String(config?.stopLossPercent ?? "1.5"));

    // ★ 実際のYahoo Financeデータを使ったシミュレーション実行
    console.log(`[daily-simulation] Fetching real J-Quants data for ${dateStr}...`);
    const simResult = await generateRealDailyReport(dateStr, rsiUpper, rsiLower, stopLossPercent);

    const dataSource = simResult.isRealData
      ? `実際の株価データ (${simResult.realDataCount}銘柄)`
      : "架空データ（市場データ取得失敗のためフォールバック）";

    console.log(`[daily-simulation] Data source: ${dataSource}`);
    console.log(`[daily-simulation] Real data: ${simResult.realDataCount} stocks, isRealData=${simResult.isRealData}`);

    // 実データが1銘柄も取得できなかった場合は警告ログを出す
    if (!simResult.isRealData) {
      console.error(`[daily-simulation] WARNING: All stocks fell back to simulated data! Check Yahoo Finance API.`);
    }

    // AI分析サマリーの生成
    let aiSummary: string | undefined;
    try {
      const lossStocks = simResult.stockReports
        .filter((r) => r.profitAmount < 0)
        .map(
          (r) =>
            `${r.name}(${r.symbol}): ${r.profitAmount.toLocaleString()}円, 勝率${(r.winRate * 100).toFixed(0)}%`
        )
        .join(", ");

      const winStocks = simResult.stockReports
        .filter((r) => r.profitAmount >= 0)
        .map((r) => `${r.name}(${r.symbol}): +${r.profitAmount.toLocaleString()}円`)
        .join(", ");

      const prompt = `あなたは株式デイトレードのAIアドバイザーです。
以下の${dateStr}の実際の株価データを使ったシミュレーション結果を分析し、改善提案を日本語で200文字以内で簡潔にまとめてください。

【本日の結果】（${dataSource}）
- 総合損益: ${simResult.totalProfitAmount.toLocaleString()}円 (${(simResult.totalProfitRate * 100).toFixed(2)}%)
- 全体勝率: ${(simResult.overallWinRate * 100).toFixed(1)}%
- 使用パラメータ: RSI上限${rsiUpper} / RSI下限${rsiLower} / 損切り${stopLossPercent}%
- 利益銘柄: ${winStocks || "なし"}
- 損失銘柄: ${lossStocks || "なし"}

改善提案（200文字以内）:`;

      const response = await invokeLLM({
        messages: [{ role: "user", content: prompt }],
      });
      const rawContent = response.choices[0]?.message?.content;
      aiSummary = typeof rawContent === "string" ? rawContent : undefined;
    } catch (e) {
      console.warn("[daily-simulation] AI summary generation failed:", e);
    }

    // データベースに保存
    const savedReport = await saveDailyReport(
      {
        reportDate: simResult.date,
        totalInitialCapital: simResult.totalInitialCapital,
        totalFinalBalance: simResult.totalFinalBalance,
        totalProfitAmount: simResult.totalProfitAmount,
        totalProfitRate: simResult.totalProfitRate.toString(),
        totalWinCount: simResult.totalWinCount,
        totalLossCount: simResult.totalLossCount,
        overallWinRate: simResult.overallWinRate.toString(),
        rsiUpper,
        rsiLower,
        stopLossPercent: stopLossPercent.toString(),
        aiSummary: aiSummary
          ? `[${dataSource}]\n${aiSummary}`
          : `[${dataSource}]`,
        isAutoGenerated: true,
      },
      simResult.stockReports.map((r) => ({
        symbol: r.symbol,
        name: r.name,
        initialCapital: r.initialCapital,
        finalBalance: r.finalBalance,
        profitAmount: r.profitAmount,
        profitRate: r.profitRate.toString(),
        tradesCount: r.tradesCount,
        winCount: r.winCount,
        winRate: r.winRate.toString(),
        trades: r.trades,
        lossCauses: r.lossCauses,
        countermeasures: r.countermeasures,
        signals: r.signals ?? [],
        isRealData: r.isRealData ?? false,
      }))
    );

    // AIによるアルゴリズム自動改善（週に1回程度、金曜日に実行）
    // targetDateは前営業日なので、金曜日（UTCで判定）なら実行
    if (targetDate.getUTCDay() === 5) {
      try {
        console.log("[daily-simulation] Running weekly algorithm improvement (Friday)");
        const stats = await getRecentStats(7);

        const prompt = `あなたは株式デイトレードのアルゴリズム最適化AIです。
直近7日間の実際の株価データを使ったシミュレーション結果を分析し、パラメータ改善案をJSON形式で返してください。

【現在のパラメータ】
- RSI上限: ${rsiUpper}
- RSI下限: ${rsiLower}
- 損切り率: ${stopLossPercent}%

【直近7日間の成績】
- 平均勝率: ${(stats.avgWinRate * 100).toFixed(1)}%
- 平均損益率: ${(stats.avgProfitRate * 100).toFixed(2)}%

目標勝率は80〜90%です。

以下のJSON形式で回答してください:
{
  "newRsiUpper": <数値 55-90>,
  "newRsiLower": <数値 10-45>,
  "newStopLossPercent": <数値 0.5-5.0>,
  "reason": "<改善理由を100文字以内で>"
}`;

        const response = await invokeLLM({
          messages: [{ role: "user", content: prompt }],
          response_format: {
            type: "json_schema",
            json_schema: {
              name: "algorithm_improvement",
              strict: true,
              schema: {
                type: "object",
                properties: {
                  newRsiUpper: { type: "number" },
                  newRsiLower: { type: "number" },
                  newStopLossPercent: { type: "number" },
                  reason: { type: "string" },
                },
                required: ["newRsiUpper", "newRsiLower", "newStopLossPercent", "reason"],
                additionalProperties: false,
              },
            },
          },
        });

        const rawContent = response.choices[0]?.message?.content;
        const content = typeof rawContent === "string" ? rawContent : null;
        if (content) {
          const parsed = JSON.parse(content);
          const newParams = {
            newRsiUpper: Math.min(90, Math.max(55, parsed.newRsiUpper)),
            newRsiLower: Math.min(45, Math.max(10, parsed.newRsiLower)),
            newStopLossPercent: Math.min(5.0, Math.max(0.5, parsed.newStopLossPercent)),
            reason: parsed.reason,
          };

          await saveAlgorithmImprovement({
            dailyReportId: savedReport.id,
            prevRsiUpper: rsiUpper,
            prevRsiLower: rsiLower,
            prevStopLossPercent: String(stopLossPercent),
            newRsiUpper: newParams.newRsiUpper,
            newRsiLower: newParams.newRsiLower,
            newStopLossPercent: String(newParams.newStopLossPercent),
            improvementReason: newParams.reason,
          });

          await updateAlgorithmConfig({
            rsiUpper: newParams.newRsiUpper,
            rsiLower: newParams.newRsiLower,
            stopLossPercent: String(newParams.newStopLossPercent),
          });

          console.log("[daily-simulation] Algorithm improved:", newParams.reason);
        }
      } catch (e) {
        console.warn("[daily-simulation] Weekly algorithm improvement failed:", e);
      }
    }

    // オーナーへの通知
    const profitStr =
      simResult.totalProfitAmount >= 0
        ? `+${simResult.totalProfitAmount.toLocaleString()}円`
        : `${simResult.totalProfitAmount.toLocaleString()}円`;
    const winRateStr = `${(simResult.overallWinRate * 100).toFixed(1)}%`;

    await notifyOwner({
      title: `📊 ${dateStr} デイリーシミュレーション完了（実データ）`,
      content: `本日の結果: 損益 ${profitStr} | 勝率 ${winRateStr} | ${dataSource}\n${aiSummary ?? ""}`,
    });

    console.log(
      `[daily-simulation] Completed for ${dateStr}: profit=${simResult.totalProfitAmount}, winRate=${simResult.overallWinRate}`
    );

    return res.json({
      ok: true,
      date: dateStr,
      profitAmount: simResult.totalProfitAmount,
      winRate: simResult.overallWinRate,
      dataSource,
    });
  } catch (error) {
    console.error("[daily-simulation] Handler error:", error);
    return res.status(500).json({
      error: String(error),
      stack: error instanceof Error ? error.stack : undefined,
      context: { url: req.url, taskUid: "unknown" },
      timestamp: new Date().toISOString(),
    });
  }
}

/**
 * オーナー専用の手動シミュレーション実行ハンドラー
 * POST /api/admin/manual-simulation
 * ヘッダー: x-owner-key: <BUILT_IN_FORGE_API_KEY>
 */
export async function manualSimulationHandler(req: Request, res: Response) {
  // オーナーAPIキー認証
  const ownerKey = req.headers["x-owner-key"];
  const expectedKey = process.env.BUILT_IN_FORGE_API_KEY;
  if (!ownerKey || ownerKey !== expectedKey) {
    return res.status(403).json({ error: "Unauthorized: invalid owner key" });
  }

  try {
    const today = new Date();
    const dateStr = today.toISOString().slice(0, 10);
    console.log(`[manual-simulation] Running REAL DATA simulation for ${dateStr}`);

    // 現在のアルゴリズム設定を取得
    const config = await getAlgorithmConfig();
    const rsiUpper = config?.rsiUpper ?? 70;
    const rsiLower = config?.rsiLower ?? 30;
    const stopLossPercent = parseFloat(String(config?.stopLossPercent ?? "1.5"));

    // ★ 実際のYahoo Financeデータを使ったシミュレーション実行
    console.log(`[manual-simulation] Fetching real Yahoo Finance data for ${dateStr}...`);
    const simResult = await generateRealDailyReport(dateStr, rsiUpper, rsiLower, stopLossPercent);

    const dataSource = `実際の株価データ (${simResult.realDataCount}銘柄)`;
    console.log(`[manual-simulation] Data source: ${dataSource}`);

    // AI分析サマリーの生成
    let aiSummary: string | undefined;
    try {
      const lossStocks = simResult.stockReports
        .filter((r) => r.profitAmount < 0)
        .map(
          (r) =>
            `${r.name}(${r.symbol}): ${r.profitAmount.toLocaleString()}円, 勝率${(r.winRate * 100).toFixed(0)}%`
        )
        .join(", ");

      const winStocks = simResult.stockReports
        .filter((r) => r.profitAmount >= 0)
        .map((r) => `${r.name}(${r.symbol}): +${r.profitAmount.toLocaleString()}円`)
        .join(", ");

      const prompt = `あなたは株式デイトレードのAIアドバイザーです。
以下の${dateStr}の実際の株価データを使ったシミュレーション結果を分析し、改善提案を日本語で200文字以内で簡潔にまとめてください。

【本日の結果】（${dataSource}）
- 総合損益: ${simResult.totalProfitAmount.toLocaleString()}円 (${(simResult.totalProfitRate * 100).toFixed(2)}%)
- 全体勝率: ${(simResult.overallWinRate * 100).toFixed(1)}%
- 使用パラメータ: RSI上限${rsiUpper} / RSI下限${rsiLower} / 損切り${stopLossPercent}%
- 利益銘柄: ${winStocks || "なし"}
- 損失銘柄: ${lossStocks || "なし"}

改善提案（200文字以内）:`;

      const response = await invokeLLM({
        messages: [{ role: "user", content: prompt }],
      });
      const rawContent = response.choices[0]?.message?.content;
      aiSummary = typeof rawContent === "string" ? rawContent : undefined;
    } catch (e) {
      console.warn("[manual-simulation] AI summary generation failed:", e);
    }

    // データベースに保存（べき等: 同じ日付で再実行すると上書き）
    const savedReport = await saveDailyReport(
      {
        reportDate: simResult.date,
        totalInitialCapital: simResult.totalInitialCapital,
        totalFinalBalance: simResult.totalFinalBalance,
        totalProfitAmount: simResult.totalProfitAmount,
        totalProfitRate: simResult.totalProfitRate.toString(),
        totalWinCount: simResult.totalWinCount,
        totalLossCount: simResult.totalLossCount,
        overallWinRate: simResult.overallWinRate.toString(),
        rsiUpper,
        rsiLower,
        stopLossPercent: stopLossPercent.toString(),
        aiSummary: aiSummary
          ? `[${dataSource}]\n${aiSummary}`
          : `[${dataSource}]`,
        isAutoGenerated: false,
      },
      simResult.stockReports.map((r) => ({
        symbol: r.symbol,
        name: r.name,
        initialCapital: r.initialCapital,
        finalBalance: r.finalBalance,
        profitAmount: r.profitAmount,
        profitRate: r.profitRate.toString(),
        tradesCount: r.tradesCount,
        winCount: r.winCount,
        winRate: r.winRate.toString(),
        trades: r.trades,
        lossCauses: r.lossCauses,
        countermeasures: r.countermeasures,
        signals: r.signals ?? [],
        isRealData: r.isRealData ?? false,
      }))
    );

    // オーナーへの通知
    const profitStr =
      simResult.totalProfitAmount >= 0
        ? `+${simResult.totalProfitAmount.toLocaleString()}円`
        : `${simResult.totalProfitAmount.toLocaleString()}円`;
    const winRateStr = `${(simResult.overallWinRate * 100).toFixed(1)}%`;

    await notifyOwner({
      title: `📊 ${dateStr} 手動シミュレーション完了（実データ）`,
      content: `本日の結果: 損益 ${profitStr} | 勝率 ${winRateStr} | ${dataSource}\n${aiSummary ?? ""}`,
    });

    console.log(
      `[manual-simulation] Completed for ${dateStr}: profit=${simResult.totalProfitAmount}, winRate=${simResult.overallWinRate}`
    );

    return res.json({
      ok: true,
      date: dateStr,
      profitAmount: simResult.totalProfitAmount,
      winRate: simResult.overallWinRate,
      dataSource,
      stockReports: simResult.stockReports.map((r) => ({
        symbol: r.symbol,
        name: r.name,
        profitAmount: r.profitAmount,
        profitRate: r.profitRate,
        winRate: r.winRate,
        tradesCount: r.tradesCount,
        winCount: r.winCount,
        lossCount: r.lossCount,
        isRealData: r.isRealData,
      })),
      aiSummary,
      reportId: savedReport.id,
    });
  } catch (error) {
    console.error("[manual-simulation] Handler error:", error);
    return res.status(500).json({
      error: String(error),
      stack: error instanceof Error ? error.stack : undefined,
      timestamp: new Date().toISOString(),
    });
  }
}

/**
 * kabuステーション® Premiumプラン期限リマインドハンドラー
 * POST /api/scheduled/kabu-plan-reminder
 * 毎日 JST 9:00（UTC 0:00）に実行し、期限7日前ならOutlookメールで通知する
 */
export async function kabuPlanReminderHandler(req: Request, res: Response) {
  try {
    // Heartbeat認証
    const user = await sdk.authenticateRequest(req);
    if (!user.isCron) {
      return res.status(403).json({ error: "cron-only endpoint" });
    }

    const { getKabuPlanSettings, markKabuPlanReminderSent } = await import("./db");

    const settings = await getKabuPlanSettings();
    if (!settings) {
      console.log("[kabu-plan-reminder] No plan settings found, skipping.");
      return res.json({ ok: true, skipped: "no-settings" });
    }

    const today = new Date();
    const todayStr = today.toISOString().slice(0, 10);
    const expiresDate = new Date(settings.planExpiresAt + "T00:00:00Z");
    const daysUntilExpiry = Math.ceil((expiresDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));

    console.log(`[kabu-plan-reminder] Plan: ${settings.planType}, expires: ${settings.planExpiresAt}, days left: ${daysUntilExpiry}, reminderSent: ${settings.reminderSent}`);

    // 期限切れ済みまたは7日より先はスキップ
    if (daysUntilExpiry > 7) {
      return res.json({ ok: true, skipped: "too-early", daysUntilExpiry });
    }

    // すでにリマインド送信済みかつ期限日が変わっていない場合はスキップ
    if (settings.reminderSent) {
      return res.json({ ok: true, skipped: "already-sent", daysUntilExpiry });
    }

    // Premiumプランの継続条件をメール本文に含める
    const premiumConditions = `
【Premiumプラン継続条件（いずれか1つを達成）】
1. 当月の信用取引「大口優遇シルバープラン以上」が適用されている
2. 前月の先物・オプション取引手数料が11万円以上（税込）
3. 前月の米国株取引手数料が11万円以上（税込）
4. 前月の全商品の預り資産が5,000万円以上

【Professionalプランへの自動降格について】
Premiumプランの条件を満たさない場合、翌営業日よりProfessionalプランが適用されます。
ProfessionalプランでもkabuステーションAPIは引き続き利用可能です。

【Professionalプラン継続条件】
・信用取引口座または先物オプション取引口座を開設済み
・前々々月〜前営業日の間に当社全取引で約定が1回以上ある
`;

    const subject = daysUntilExpiry <= 0
      ? `⚠️ kabuステーション® Premiumプランが本日期限切れです`
      : `⚠️ kabuステーション® Premiumプラン期限まで残り${daysUntilExpiry}日（${settings.planExpiresAt}）`;

    const body = `${subject}

現在のプラン: ${settings.planType === "premium" ? "Premiumプラン" : settings.planType === "professional" ? "Professionalプラン" : "通常プラン"}
有効期限: ${settings.planExpiresAt}
残り日数: ${daysUntilExpiry <= 0 ? "期限切れ" : `${daysUntilExpiry}日`}
確認日: ${todayStr}

${premiumConditions}

${settings.note ? `【メモ】\n${settings.note}\n` : ""}
---
このメールはStock Alert Appの自動リマインド機能から送信されています。
期限日の更新はアプリのアルゴリズム設定ページから行えます。
`;

    // Outlookメールで送信（MCP経由）
    // NOTE: MCPはサーバーサイドから直接呼び出せないため、notifyOwnerで代替通知する
    // 実際のOutlookメール送信はtRPC経由でフロントエンドから行う設計
    await notifyOwner({
      title: subject,
      content: body,
    });

    // リマインド送信済みフラグを立てる
    await markKabuPlanReminderSent(settings.id);

    console.log(`[kabu-plan-reminder] Reminder sent for plan expiry: ${settings.planExpiresAt}`);
    return res.json({ ok: true, reminderSent: true, daysUntilExpiry, planExpiresAt: settings.planExpiresAt });

  } catch (error) {
    console.error("[kabu-plan-reminder] Handler error:", error);
    return res.status(500).json({
      error: String(error),
      stack: error instanceof Error ? error.stack : undefined,
      context: { url: req.url, taskUid: "kabu-plan-reminder" },
      timestamp: new Date().toISOString(),
    });
  }
}

/**
 * リアルタイムシミュレーション 大引け後レポートハンドラー
 * POST /api/scheduled/rt-daily-report
 * 毎平日 JST 16:00（UTC 7:00）に実行し、当日の架空取引結果をOutlookメールで送信する
 */
export async function rtDailyReportHandler(req: Request, res: Response) {
  try {
    // Heartbeat認証
    const user = await sdk.authenticateRequest(req);
    if (!user.isCron) {
      return res.status(403).json({ error: "cron-only endpoint" });
    }

    // 当日の日付（JST）を取得
    const now = new Date();
    const jstNow = new Date(now.getTime() + 9 * 60 * 60 * 1000);
    const todayStr = jstNow.toISOString().slice(0, 10);

    console.log(`[rt-daily-report] Running end-of-day report for: ${todayStr}`);

    const {
      getRtTradesForDate,
      getRtDailySummary,
      markRtDailySummaryReportSent,
      getRtOpenPositionsFromDb,
      getRtCandles,
    } = await import("./db");

    const {
      forceCloseAllPositions,
      getOpenPositions,
    } = await import("./realtimeSimEngine");

    // 残存ポジションを強制決済
    // まずメモリ上のポジションを確認。メモリが空の場合（サーバー再起動等）はDBから復元する。
    let openPositions = getOpenPositions();
    if (openPositions.length === 0) {
      // DBから未決済ポジションを復元
      const dbOpenTrades = await getRtOpenPositionsFromDb(todayStr);
      if (dbOpenTrades.length > 0) {
        console.log(`[rt-daily-report] Memory was empty. Restoring ${dbOpenTrades.length} open positions from DB...`);
        // realtimeSimEngineの openPositions Mapに復元する
        const { restoreOpenPositions } = await import("./realtimeSimEngine");
        restoreOpenPositions(dbOpenTrades);
        openPositions = getOpenPositions();
      }
    }

    if (openPositions.length > 0) {
      console.log(`[rt-daily-report] Force closing ${openPositions.length} open positions...`);
      const closingPrices = new Map<string, number>();
      for (const pos of openPositions) {
        // 当日の最後の1分足の終値を引け値として使用する
        const candles = await getRtCandles(pos.symbol, todayStr);
        const lastCandle = candles[candles.length - 1];
        const closePrice = lastCandle ? Number(lastCandle.close) : pos.entryPrice;
        closingPrices.set(pos.symbol, closePrice);
        console.log(`[rt-daily-report] ${pos.symbol}: last candle close = ${closePrice}円 (entry: ${pos.entryPrice}円)`);
      }
      await forceCloseAllPositions(todayStr, closingPrices);
    }

    // 当日の取引ログを取得
    const trades = await getRtTradesForDate(todayStr);
    const summary = await getRtDailySummary(todayStr);

    // 取引がない場合はスキップ
    if (trades.length === 0 && !summary) {
      console.log(`[rt-daily-report] No trades for ${todayStr}, skipping report.`);
      return res.json({ ok: true, skipped: "no-trades", tradeDate: todayStr });
    }

    // 既にレポート送信済みの場合はスキップ
    if (summary?.reportSent) {
      console.log(`[rt-daily-report] Report already sent for ${todayStr}, skipping.`);
      return res.json({ ok: true, skipped: "already-sent", tradeDate: todayStr });
    }

    // 決済済みトレードを集計
    const closedTrades = trades.filter(t => t.action === "sell" || t.action === "cover");
    const totalPnl = closedTrades.reduce((sum, t) => sum + (t.pnl ?? 0), 0);
    const winTrades = closedTrades.filter(t => (t.pnl ?? 0) > 0);
    const lossTrades = closedTrades.filter(t => (t.pnl ?? 0) <= 0);
    const winRate = closedTrades.length > 0 ? (winTrades.length / closedTrades.length * 100).toFixed(1) : "0.0";

    // 銘柄別集計
    const symbolPnl = new Map<string, number>();
    for (const t of closedTrades) {
      symbolPnl.set(t.symbol, (symbolPnl.get(t.symbol) ?? 0) + (t.pnl ?? 0));
    }

    // メール本文を生成
    const pnlSign = totalPnl >= 0 ? "+" : "";
    const subject = `📊 リアルタイム取引シミュレーション結果 ${todayStr} (${pnlSign}${totalPnl.toLocaleString()}円)`;

    const symbolLines = Array.from(symbolPnl.entries())
      .sort((a, b) => b[1] - a[1])
      .map(([sym, pnl]) => {
        const sign = pnl >= 0 ? "+" : "";
        return `  ${sym}: ${sign}${pnl.toLocaleString()}円`;
      })
      .join("\n");

    const tradeLines = closedTrades
      .slice(0, 20) // 最大20件
      .map(t => {
        const pnlStr = t.pnl !== null ? (t.pnl >= 0 ? `+${t.pnl.toLocaleString()}` : t.pnl.toLocaleString()) : "-";
        return `  [${t.tradeTime}] ${t.symbol} ${t.action.toUpperCase()} @${Number(t.price).toLocaleString()}円 ×${t.shares}株 損益:${pnlStr}円`;
      })
      .join("\n");

    const body = `${subject}

【当日サマリー】
対象日: ${todayStr}
元金: ${(summary?.initialCapital ?? 15_000_000).toLocaleString()}円（5銘柄 × 300万円）
当日損益: ${pnlSign}${totalPnl.toLocaleString()}円
取引回数: ${closedTrades.length}回（勝: ${winTrades.length} / 負: ${lossTrades.length}）
勝率: ${winRate}%

【銘柄別損益】
${symbolLines || "  （取引なし）"}

【取引詳細（最大20件）】
${tradeLines || "  （取引なし）"}

---
このメールはStock Alert Appのリアルタイムシミュレーション機能から自動送信されています。
`;

    // notifyOwner で通知（Outlookメール代替）
    await notifyOwner({
      title: subject,
      content: body,
    });

    // レポート送信済みフラグを立てる
    await markRtDailySummaryReportSent(todayStr);

    console.log(`[rt-daily-report] Report sent for ${todayStr}: totalPnl=${totalPnl}, trades=${closedTrades.length}`);
    return res.json({
      ok: true,
      tradeDate: todayStr,
      totalPnl,
      tradesCount: closedTrades.length,
      winRate,
    });

  } catch (error) {
    console.error("[rt-daily-report] Handler error:", error);
    return res.status(500).json({
      error: String(error),
      stack: error instanceof Error ? error.stack : undefined,
      context: { url: req.url, taskUid: "rt-daily-report" },
      timestamp: new Date().toISOString(),
    });
  }
}

// ============================================================
// サーバーウォームアップ（毎平日 JST 8:44 = UTC 23:44 前日）
// Manusサンドボックスのスリープを防ぎ、取引時間前にサーバーを起動状態にする
// ============================================================
export async function serverWarmupHandler(req: Request, res: Response) {
  try {
    const user = await sdk.authenticateRequest(req);
    if (!user.isCron) {
      return res.status(403).json({ error: "cron-only" });
    }

    const nowJst = new Date(Date.now() + 9 * 60 * 60 * 1000);
    const jstStr = nowJst.toISOString().replace("T", " ").substring(0, 19) + " JST";
    console.log(`[server-warmup] Warmup triggered at ${jstStr}`);

    // DBへの軽量クエリでDBコネクションもウォームアップ
    const { rtCandles } = await import("../drizzle/schema");
    const { sql } = await import("drizzle-orm");
    const dbInstance = await getDb();
    const countResult = dbInstance
      ? await dbInstance.select({ count: sql<number>`count(*)` }).from(rtCandles).limit(1)
      : [];
    const candleCount = countResult[0]?.count ?? 0;

    console.log(`[server-warmup] Server is warm. DB candle count: ${candleCount}`);

    return res.json({
      ok: true,
      message: "Server warmed up",
      time: jstStr,
      dbCandleCount: candleCount,
    });
  } catch (error) {
    console.error("[server-warmup] Handler error:", error);
    return res.status(500).json({
      error: String(error),
      stack: error instanceof Error ? error.stack : undefined,
      context: { url: req.url },
      timestamp: new Date().toISOString(),
    });
  }
}


// ============================================================
// 3山v2シグナル日次レポート（毎平日 JST 16:00 = UTC 07:00）
// 当日の3山v2シグナル（LONG/SHORT）の仮想取引結果を通知する
// ============================================================
export async function threePeakDailyReportHandler(req: Request, res: Response) {
  try {
    // Heartbeat認証
    const user = await sdk.authenticateRequest(req);
    if (!user.isCron) {
      return res.status(403).json({ error: "cron-only endpoint" });
    }

    // 当日の日付（JST）を取得
    const now = new Date();
    const jstNow = new Date(now.getTime() + 9 * 60 * 60 * 1000);
    const todayStr = jstNow.toISOString().slice(0, 10);

    console.log(`[3peak-report] Running 3-peak v2 daily report for: ${todayStr}`);

    const { getThreePeakSignalsForDate } = await import("./threePeakDetector");

    const signals = await getThreePeakSignalsForDate(todayStr);

    // シグナルがない場合も通知（「本日はシグナルなし」）
    const shortSignals = signals.filter(s => s.direction === "short");
    const longSignals = signals.filter(s => s.direction === "long");

    const totalSignals = signals.length;
    const completedSignals = signals.filter(s => s.exitReason !== "pending");
    const totalPnl = completedSignals.reduce((sum, s) => sum + (s.virtualPnl ?? 0), 0);
    const winSignals = completedSignals.filter(s => (s.virtualPnl ?? 0) > 0);
    const lossSignals = completedSignals.filter(s => (s.virtualPnl ?? 0) <= 0);
    const winRate = completedSignals.length > 0
      ? (winSignals.length / completedSignals.length * 100).toFixed(1)
      : "N/A";

    const pnlSign = totalPnl >= 0 ? "+" : "";
    const subject = totalSignals > 0
      ? `🔺 3山v2シグナルレポート ${todayStr} (${totalSignals}件, ${pnlSign}${totalPnl.toLocaleString()}円)`
      : `🔺 3山v2シグナルレポート ${todayStr} (シグナルなし)`;

    // シグナル詳細
    const signalLines = signals.map(s => {
      const dir = s.direction === "short" ? "SHORT" : "LONG";
      const pnlStr = s.virtualPnl !== null
        ? (s.virtualPnl >= 0 ? `+${s.virtualPnl.toLocaleString()}` : s.virtualPnl.toLocaleString())
        : "未決済";
      const exitStr = s.exitReason === "pending"
        ? "保有中"
        : `${s.exitReason.toUpperCase()} @${s.exitPrice?.toLocaleString() ?? "-"}円 (${s.exitTime ?? "-"})`;
      return `  [${s.signalTime}] ${dir} @${s.entryPrice.toLocaleString()}円 ×${s.shares}株 → ${exitStr} 損益:${pnlStr}円 [${s.holdBars ?? "-"}本]`;
    }).join("\n");

    const body = `${subject}

【3山v2シグナル サマリー】
対象日: ${todayStr}
対象銘柄: 6981（村田製作所）
シグナル数: ${totalSignals}件（SHORT: ${shortSignals.length} / LONG: ${longSignals.length}）
決済済み: ${completedSignals.length}件
仮想損益: ${pnlSign}${totalPnl.toLocaleString()}円
勝率: ${winRate}%（勝: ${winSignals.length} / 負: ${lossSignals.length}）

【シグナル詳細】
${signalLines || "  （本日シグナルなし）"}

---
※ これは3山v2ロジックのフォワードテスト（ログ記録のみ）です。
※ 実際のエントリーには使用されていません。
※ TP: 1.5% / SL: 0.5% / 仮想投資額: 100万円/件
`;

    await notifyOwner({
      title: subject,
      content: body,
    });

    // レポート送信済みフラグを立てる
    try {
      const db = await getDb();
      if (db) {
        const { rt3peakSignals } = await import("../drizzle/schema");
        const { eq, and: andOp } = await import("drizzle-orm");
        await db.update(rt3peakSignals)
          .set({ reportSent: true })
          .where(
            andOp(
              eq(rt3peakSignals.tradeDate, todayStr),
              eq(rt3peakSignals.symbol, "6981"),
            )
          );
      }
    } catch (flagErr) {
      console.warn("[3peak-report] Failed to set reportSent flag:", flagErr);
    }

    console.log(`[3peak-report] Report sent for ${todayStr}: signals=${totalSignals}, pnl=${totalPnl}`);
    return res.json({
      ok: true,
      tradeDate: todayStr,
      signalCount: totalSignals,
      totalPnl,
      winRate,
    });

  } catch (error) {
    console.error("[3peak-report] Handler error:", error);
    return res.status(500).json({
      error: String(error),
      stack: error instanceof Error ? error.stack : undefined,
      context: { url: req.url, taskUid: "3peak-daily-report" },
      timestamp: new Date().toISOString(),
    });
  }
}
