import { sql } from "drizzle-orm";
import { getDb } from "../server/db";

type Row = { tradeDate:string; tradeTime:string; action:"buy"|"sell"|"short"|"cover"; price:number; pnl:number|null; reason:string };
type Deal = { date:string; time:string; side:"LONG"|"SHORT"; label:string; confidence:"strong"|"medium"; band:string; pnl:number; exitTime:string; exitReason:string };
const band = (t:string) => t < "10:00" ? "寄り〜10:00" : t <= "11:27" ? "10:00〜11:27" : t < "13:30" ? "12:30〜13:30" : "13:30〜大引け";
const label = (r:string) => r.includes("大台") ? "大台割れ" : r.includes("ダウ理論") ? "ダウ更新" : r.includes("三尊") && r.includes("逆") ? "逆三尊" : r.includes("三尊") ? "三尊" : r.includes("ダブルトップ") ? "ダブルトップ" : r.includes("VWAP反発") ? "VWAP反発" : r.includes("VWAPクロス") ? "VWAPクロス" : r.includes("デッドクロス") ? "デッドクロス" : "その他";
const confidence = (r:string):"strong"|"medium" => r.includes("信頼度：強") ? "strong" : "medium";
function summary(title:string, deals:Deal[]) { const wins=deals.filter(d=>d.pnl>0),pnl=deals.reduce((s,d)=>s+d.pnl,0),gp=wins.reduce((s,d)=>s+d.pnl,0),gl=-deals.filter(d=>d.pnl<0).reduce((s,d)=>s+d.pnl,0); console.log(`${title}: ${deals.length}件 ${wins.length}勝${deals.length-wins.length}敗 勝率${(wins.length/Math.max(deals.length,1)*100).toFixed(1)}% ${pnl>=0?"+":""}${pnl.toFixed(0)}円 PF${gl?(gp/gl).toFixed(2):"∞"}`); }
async function main(){ const db=await getDb();if(!db)throw new Error("DB接続に失敗");const r=await db.execute(sql`SELECT tradeDate, tradeTime, action, price, pnl, reason FROM rt_trades WHERE symbol='5803' ORDER BY tradeDate, tradeTime, id`);const rows=(r as unknown as [Array<Record<string,unknown>>])[0].map(x=>({tradeDate:String(x.tradeDate),tradeTime:String(x.tradeTime),action:String(x.action) as Row["action"],price:Number(x.price),pnl:x.pnl===null?null:Number(x.pnl),reason:String(x.reason)}));const deals:Deal[]=[];let entry:Row|null=null;for(const row of rows){if(row.action==="buy"||row.action==="short"){entry=row;continue;}if(entry&&row.pnl!==null){deals.push({date:entry.tradeDate,time:entry.tradeTime,side:entry.action==="buy"?"LONG":"SHORT",label:label(entry.reason),confidence:confidence(entry.reason),band:band(entry.tradeTime),pnl:row.pnl,exitTime:row.tradeTime,exitReason:row.reason});entry=null;}}
 console.log("フジクラ（5803）既存取引の勝敗分解（KABUステーション実取引ログ）");summary("全体",deals);for(const key of ["LONG","SHORT"] as const)summary(key,deals.filter(d=>d.side===key));console.log("--- シグナル別 ---");for(const key of [...new Set(deals.map(d=>d.label))])summary(key,deals.filter(d=>d.label===key));console.log("--- 時間帯別 ---");for(const key of ["寄り〜10:00","10:00〜11:27","12:30〜13:30","13:30〜大引け"])summary(key,deals.filter(d=>d.band===key));console.log("--- 信頼度別 ---");for(const key of ["strong","medium"] as const)summary(key,deals.filter(d=>d.confidence===key));console.log("--- 個別取引 ---");for(const d of deals)console.log(`${d.date} ${d.time} ${d.side} ${d.label}/${d.confidence}/${d.band} -> ${d.exitTime} ${d.pnl>=0?"+":""}${d.pnl}円 (${d.exitReason})`);process.exit(0);}
main().catch(e=>{console.error(e);process.exit(1)});
