import { sql } from "drizzle-orm";
import { getDb } from "../server/db";
type B={signal?:string;buyPressureRatio?:number};type C={tradeDate:string;candleTime:string;open:number;high:number;low:number;close:number;volume:number;boardSnapshot:unknown};type T={date:string;time:string;exitTime:string;outcome:string;pnl:number};
const avg=(x:number[])=>x.reduce((s,v)=>s+v,0)/x.length;const pct=(a:number,b:number)=>(a/b-1)*100;const board=(c:C):B|null=>typeof c.boardSnapshot==="string"?JSON.parse(c.boardSnapshot):c.boardSnapshot as B|null;
function clean(rows:C[]){const m=new Map<string,C[]>();for(const r of rows){const d=m.get(r.tradeDate)??[],p=d.at(-1);if(!p||!(r.low<p.close*.5||r.high>p.close*1.5))d.push(r);m.set(r.tradeDate,d)}return [...m.values()].filter(d=>d.length>100).slice(-40)}
function slope(d:C[],i:number){return pct(avg(d.slice(i-7,i+1).map(x=>x.close)),avg(d.slice(i-9,i-1).map(x=>x.close)))}
function exit(d:C[],i:number):Omit<T,"date"|"time">{const e=d[i].close,sl=e*.995,tp=e*1.005;for(let j=i+1;j<d.length&&d[j].candleTime<="15:25";j++){if(d[j].low<=sl)return{exitTime:d[j].candleTime,outcome:"SL",pnl:(sl-e)*100};if(d[j].high>=tp)return{exitTime:d[j].candleTime,outcome:"TP",pnl:(tp-e)*100}}const last=[...d].reverse().find(x=>x.candleTime<="15:25")!;return{exitTime:last.candleTime,outcome:"時間決済",pnl:(last.close-e)*100}}
type P={mDrop:number;bounce:number;vol:number;bpr:number;start:string};
function signal(d:C[],p:P):T|null{const open=d[0].open,am=d.filter(x=>x.candleTime<="11:27").at(-1)!;for(let i=20;i<d.length;i++){const c=d[i];if(c.candleTime<p.start||c.candleTime>"14:00")continue;const low=Math.min(...d.slice(0,i+1).map(x=>x.low)),prior10=Math.max(...d.slice(i-10,i).map(x=>x.high)),vr=c.volume/avg(d.slice(i-20,i).map(x=>x.volume)),b=board(c);if(pct(am.close,open)<=-p.mDrop&&pct(c.close,low)>=p.bounce&&slope(d,i)>=.02&&c.high>prior10&&c.close>c.open&&vr>=p.vol&&b?.signal!=="sell_pressure"&&(b?.buyPressureRatio??0)<=p.bpr)return{date:c.tradeDate,time:c.candleTime,...exit(d,i)}}return null}
function stat(ts:T[]){const w=ts.filter(t=>t.pnl>0).length,p=ts.reduce((s,t)=>s+t.pnl,0),gp=ts.filter(t=>t.pnl>0).reduce((s,t)=>s+t.pnl,0),gl=-ts.filter(t=>t.pnl<0).reduce((s,t)=>s+t.pnl,0);return{n:ts.length,w,r:ts.length?w/ts.length*100:0,p,pf:gl?gp/gl:Infinity}}
async function main(){const db=await getDb();if(!db)throw Error("DB接続に失敗");const r=await db.execute(sql`SELECT tradeDate,candleTime,open,high,low,close,volume,boardSnapshot FROM rt_candles WHERE symbol='5803' ORDER BY tradeDate,candleTime`);const ds=clean((r as any)[0].map((x:any)=>({...x,tradeDate:String(x.tradeDate),candleTime:String(x.candleTime),open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume}))as C[]),out:any[]=[];for(const start of ["12:50","13:00"])for(const mDrop of [.5,1,1.5,2])for(const bounce of [.3,.5,.8])for(const vol of [.5,.7,.8,1,1.2])for(const bpr of [1,1.2,1.5,99]){const p={start,mDrop,bounce,vol,bpr},t=ds.map(d=>signal(d,p)).filter(Boolean)as T[],s=stat(t),d820=t.find(x=>x.date==="2026-08-20"&&x.time>="12:42"&&x.time<="13:15");if(d820)out.push({p,t,s})}out.sort((a,b)=>b.s.r-a.s.r||b.s.p-a.s.p);console.log(`フジクラ後場反転LONG精密化: ${ds[0][0].tradeDate}〜${ds.at(-1)![0].tradeDate}、40営業日。8/20の12:42〜13:15で発火する候補のみ。`);for(const x of out.slice(0,20)){const p=x.p;console.log(`開始${p.start}/前場落${p.mDrop}%/反発${p.bounce}%/vol${p.vol}/BPR≤${p.bpr===99?"なし":p.bpr}: ${x.s.n}件 ${x.s.w}勝${x.s.n-x.s.w}敗 勝率${x.s.r.toFixed(1)}% ${x.s.p>=0?"+":""}${x.s.p.toFixed(0)}円 PF${x.s.pf.toFixed(2)} | 8/20 ${x.t.find((z:T)=>z.date==="2026-08-20")?.time}`)}const best=out[0];console.log("--- 最上位明細 ---");best.t.forEach((t:T)=>console.log(`${t.date} ${t.time}->${t.exitTime} ${t.outcome} ${t.pnl>=0?"+":""}${t.pnl.toFixed(0)}円`));process.exit(0)}
main().catch(e=>{console.error(e);process.exit(1)});
