import { sql } from "drizzle-orm";
import { getDb } from "../server/db";

type Board = { signal?: string; buyPressureRatio?: number };
type C = { tradeDate:string; candleTime:string; open:number; high:number; low:number; close:number; volume:number; boardSnapshot:unknown };
type T = { date:string; time:string; kind:string; exitTime:string; outcome:string; pnl:number };
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length; const pct=(a:number,b:number)=>(a/b-1)*100;
const bd=(c:C):Board|null=>typeof c.boardSnapshot === "string" ? JSON.parse(c.boardSnapshot) : c.boardSnapshot as Board|null;
function clean(rows:C[]){const m=new Map<string,C[]>();for(const r of rows){const d=m.get(r.tradeDate)??[],p=d.at(-1);if(!p||!(r.low<p.close*.5||r.high>p.close*1.5))d.push(r);m.set(r.tradeDate,d);}return [...m.values()].filter(d=>d.length>100).slice(-40);}
function slope(d:C[],i:number){return pct(mean(d.slice(i-7,i+1).map(x=>x.close)),mean(d.slice(i-9,i-1).map(x=>x.close)));}
function exit(d:C[],i:number,side:"long"|"short"):Omit<T,"date"|"time"|"kind">{const e=d[i].close,sl=side==="long"?e*.995:e*1.006,tp=side==="long"?e*1.005:e*.985;for(let j=i+1;j<d.length;j++){const c=d[j];if(side==="long"?c.low<=sl:c.high>=sl)return{exitTime:c.candleTime,outcome:"SL",pnl:(side==="long"?sl-e:e-sl)*100};if(side==="long"?c.high>=tp:c.low<=tp)return{exitTime:c.candleTime,outcome:"TP",pnl:(side==="long"?tp-e:e-tp)*100};}const last=d.at(-1)!;return{exitTime:last.candleTime,outcome:"大引け",pnl:(side==="long"?last.close-e:e-last.close)*100};}
function morningFade(d:C[],drop:number,vol:number):T|null{const open=d[0].open;for(let i=30;i<d.length;i++){const c=d[i];if(c.candleTime<"10:00"||c.candleTime>"11:27")continue;const first30=d.filter(x=>x.candleTime<="09:30"),earlyHigh=Math.max(...first30.map(x=>x.high)),prior10=Math.min(...d.slice(i-10,i).map(x=>x.low)),vr=c.volume/mean(d.slice(i-20,i).map(x=>x.volume));const b=bd(c);if(pct(earlyHigh,open)>=.3&&pct(earlyHigh,c.close)>=drop&&pct(c.close,open)<=-.5&&slope(d,i)<=-.02&&c.low<prior10&&c.close<c.open&&vr>=vol&&b?.signal!=="buy_pressure")return{date:c.tradeDate,time:c.candleTime,kind:"朝高値失速SHORT",...exit(d,i,"short")};}return null;}
function afternoonReversal(d:C[],mDrop:number,bounce:number,vol:number):T|null{const open=d[0].open;for(let i=30;i<d.length;i++){const c=d[i];if(c.candleTime<"12:30"||c.candleTime>"14:00")continue;const am=d.filter(x=>x.candleTime<="11:27").at(-1)!;const low=Math.min(...d.slice(0,i+1).map(x=>x.low)),prior10=Math.max(...d.slice(i-10,i).map(x=>x.high)),vr=c.volume/mean(d.slice(i-20,i).map(x=>x.volume));const b=bd(c);if(pct(am.close,open)<=-mDrop&&pct(c.close,low)>=bounce&&slope(d,i)>=.02&&c.high>prior10&&c.close>c.open&&vr>=vol&&b?.signal!=="sell_pressure")return{date:c.tradeDate,time:c.candleTime,kind:"後場反転LONG",...exit(d,i,"long")};}return null;}
function stat(ts:T[]){const w=ts.filter(t=>t.pnl>0).length,p=ts.reduce((s,t)=>s+t.pnl,0),gp=ts.filter(t=>t.pnl>0).reduce((s,t)=>s+t.pnl,0),gl=-ts.filter(t=>t.pnl<0).reduce((s,t)=>s+t.pnl,0);return{n:ts.length,w,rate:ts.length?w/ts.length*100:0,p,pf:gl?gp/gl:Infinity};}
async function main(){const db=await getDb();if(!db)throw new Error("DB接続に失敗");const r=await db.execute(sql`SELECT tradeDate,candleTime,open,high,low,close,volume,boardSnapshot FROM rt_candles WHERE symbol='5803' ORDER BY tradeDate,candleTime`);const rows=(r as unknown as [Array<Record<string,unknown>>])[0].map(x=>({...x,tradeDate:String(x.tradeDate),candleTime:String(x.candleTime),open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume}))as C[];const ds=clean(rows);console.log(`フジクラ候補検証: ${ds[0][0].tradeDate}〜${ds.at(-1)![0].tradeDate}、${ds.length}営業日、KABUステーション保存1分足、SHORT SL0.6%/TP1.5%、LONG SL0.5%/TP0.5%`);for(const type of ["short","long"] as const){const out:any[]=[];if(type==="short"){for(const drop of [.8,1,1.5,2])for(const vol of [.8,1,1.2]){const t=ds.map(d=>morningFade(d,drop,vol)).filter(Boolean)as T[];out.push({drop,vol,t,s:stat(t)});}}else{for(const mDrop of [.5,1,1.5,2])for(const bounce of [.3,.5,.8])for(const vol of [.8,1,1.2]){const t=ds.map(d=>afternoonReversal(d,mDrop,bounce,vol)).filter(Boolean)as T[];out.push({mDrop,bounce,vol,t,s:stat(t)});}}out.sort((a,b)=>b.s.p-a.s.p||b.s.rate-a.s.rate);console.log(type==="short"?"--- 朝高値失速SHORT 上位10 ---":"--- 後場反転LONG 上位10 ---");for(const x of out.slice(0,10)){const p=type==="short"?`高値落${x.drop}%/vol${x.vol}`:`前場落${x.mDrop}%/反発${x.bounce}%/vol${x.vol}`;console.log(`${p}: ${x.s.n}件 ${x.s.w}勝${x.s.n-x.s.w}敗 勝率${x.s.rate.toFixed(1)}% ${x.s.p>=0?"+":""}${x.s.p.toFixed(0)}円 PF${x.s.pf.toFixed(2)} | 8/20 ${x.t.find((z:T)=>z.date==="2026-08-20")?.time??"-"}`);}const best=out[0];console.log("明細:");for(const t of best.t)console.log(`${t.date} ${t.time} -> ${t.exitTime} ${t.outcome} ${t.pnl>=0?"+":""}${t.pnl.toFixed(0)}円`);}process.exit(0);}
main().catch(e=>{console.error(e);process.exit(1)});
