import { sql } from "drizzle-orm";
import { getDb } from "../server/db";
type B={signal?:string;buyPressureRatio?:number};type C={tradeDate:string;candleTime:string;open:number;high:number;low:number;close:number;volume:number;boardSnapshot:unknown};type T={date:string;time:string;side:"SHORT"|"LONG";kind:string;exitTime:string;outcome:string;pnl:number};
const avg=(x:number[])=>x.reduce((s,v)=>s+v,0)/x.length;const pct=(a:number,b:number)=>(a/b-1)*100;const board=(c:C):B|null=>typeof c.boardSnapshot==="string"?JSON.parse(c.boardSnapshot):c.boardSnapshot as B|null;
function clean(rows:C[]){const m=new Map<string,C[]>();for(const r of rows){const d=m.get(r.tradeDate)??[],p=d.at(-1);if(!p||!(r.low<p.close*.5||r.high>p.close*1.5))d.push(r);m.set(r.tradeDate,d)}return [...m.values()].filter(d=>d.length>100).slice(-40)}
function slope(d:C[],i:number){return pct(avg(d.slice(i-7,i+1).map(x=>x.close)),avg(d.slice(i-9,i-1).map(x=>x.close)))}
function exit(d:C[],i:number,side:"SHORT"|"LONG"):Omit<T,"date"|"time"|"side"|"kind">{const e=d[i].close,sl=side==="LONG"?e*.995:e*1.006,tp=side==="LONG"?e*1.005:e*.985,cut=d[i].candleTime<="11:27"?"11:27":"15:25";for(let j=i+1;j<d.length&&d[j].candleTime<=cut;j++){const c=d[j];if(side==="LONG"?c.low<=sl:c.high>=sl)return{exitTime:c.candleTime,outcome:"SL",pnl:(side==="LONG"?sl-e:e-sl)*100};if(side==="LONG"?c.high>=tp:c.low<=tp)return{exitTime:c.candleTime,outcome:"TP",pnl:(side==="LONG"?tp-e:e-tp)*100}}const last=[...d].reverse().find(x=>x.candleTime<=cut)!;return{exitTime:last.candleTime,outcome:"時間決済",pnl:(side==="LONG"?last.close-e:e-last.close)*100}}
function roundShort(d:C[]):T|null{const dayOpen=d[0].open;for(let i=20;i<d.length;i++){const c=d[i];if(c.candleTime<"09:45"||c.candleTime>"10:45")continue;const prev=d[i-1],round=Math.floor(prev.close/100)*100,j=i+2;if(!(prev.close>=round&&c.close<round)||j>=d.length)continue;const e=d[j],b=board(c),vr=c.volume/avg(d.slice(i-20,i).map(x=>x.volume)),body=pct(e.open,e.close),momentum=pct(e.close,d[Math.max(0,j-3)].close);if(d.slice(i,j+1).every(x=>x.close<round)&&pct(e.close,dayOpen)>=-3&&slope(d,j)<=-.02&&vr>=1.2&&b?.signal!=="buy_pressure"&&(b?.buyPressureRatio??Infinity)<=.8&&body>=0&&momentum<=0)return{date:e.tradeDate,time:e.candleTime,side:"SHORT",kind:"大台割れ継続SHORT",...exit(d,j,"SHORT")}}return null}
function afternoonLong(d:C[]):T|null{const dayOpen=d[0].open;for(let i=20;i<d.length;i++){const c=d[i];if(c.candleTime<"12:50"||c.candleTime>"14:00")continue;const am=d.filter(x=>x.candleTime<="11:27").at(-1)!;const low=Math.min(...d.slice(0,i+1).map(x=>x.low)),prior10=Math.max(...d.slice(i-10,i).map(x=>x.high)),vr=c.volume/avg(d.slice(i-20,i).map(x=>x.volume)),b=board(c);if(pct(am.close,dayOpen)<=-1&&pct(c.close,low)>=.8&&slope(d,i)>=.02&&c.high>prior10&&c.close>c.open&&vr>=.7&&b?.signal!=="sell_pressure"&&(b?.buyPressureRatio??0)<=1)return{date:c.tradeDate,time:c.candleTime,side:"LONG",kind:"後場反転LONG",...exit(d,i,"LONG")}}return null}
function stat(ts:T[]){const w=ts.filter(t=>t.pnl>0).length,p=ts.reduce((s,t)=>s+t.pnl,0),gp=ts.filter(t=>t.pnl>0).reduce((s,t)=>s+t.pnl,0),gl=-ts.filter(t=>t.pnl<0).reduce((s,t)=>s+t.pnl,0);return`${ts.length}件 ${w}勝${ts.length-w}敗 勝率${ts.length?(w/ts.length*100).toFixed(1):"0.0"}% ${p>=0?"+":""}${p.toFixed(0)}円 PF${gl?(gp/gl).toFixed(2):"∞"}`}
function integrate(ts:T[]){const ok:T[]=[];for(const day of Object.values(ts.reduce((m:Record<string,T[]>,x)=>(m[x.date]??=[]).push(x)&&m,{}))){let busy="00:00";for(const x of day.sort((a,b)=>a.time.localeCompare(b.time)))if(x.time>busy){ok.push(x);busy=x.exitTime}}return ok}
async function main(){const db=await getDb();if(!db)throw Error("DB接続に失敗");const r=await db.execute(sql`SELECT tradeDate,candleTime,open,high,low,close,volume,boardSnapshot FROM rt_candles WHERE symbol='5803' ORDER BY tradeDate,candleTime`);const ds=clean((r as any)[0].map((x:any)=>({...x,tradeDate:String(x.tradeDate),candleTime:String(x.candleTime),open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume}))as C[]);const s=ds.map(roundShort).filter(Boolean)as T[],l=ds.map(afternoonLong).filter(Boolean)as T[],all=integrate([...s,...l]),half=Math.ceil(ds.length/2),split=(ts:T[])=>[ts.filter(t=>t.date<=ds[half-1][0].tradeDate),ts.filter(t=>t.date>=ds[half][0].tradeDate)];console.log(`フジクラ候補の固定条件検証: ${ds[0][0].tradeDate}〜${ds.at(-1)![0].tradeDate}（40営業日、KABUステーション保存1分足のみ）`);console.log("SHORT: 09:45〜10:45、100円大台を3本連続で下回る、始値比-3%以内、MA8傾き≤-0.02%、出来高≥1.2倍、buy_pressure以外かつBPR≤0.8、SL0.6%/TP1.5%");console.log(`SHORT ${stat(s)} | 前半 ${stat(split(s)[0])} | 後半 ${stat(split(s)[1])}`);console.log("LONG: 12:50〜14:00、前場終値が始値比-1%以下、当日安値から0.3%以上反発、10本高値更新、MA8傾き≥0.02%、陽線、出来高≥1.2倍、sell_pressure以外、SL0.5%/TP0.5%");console.log(`LONG ${stat(l)} | 前半 ${stat(split(l)[0])} | 後半 ${stat(split(l)[1])}`);console.log(`1銘柄1ポジション統合 ${stat(all)}`);console.log("--- 明細 ---");all.forEach(t=>console.log(`${t.date} ${t.time} ${t.side} ${t.kind} -> ${t.exitTime} ${t.outcome} ${t.pnl>=0?"+":""}${t.pnl.toFixed(0)}円`));process.exit(0)}
main().catch(e=>{console.error(e);process.exit(1)});
