import { sql } from "drizzle-orm";
import { getDb } from "../server/db";
type B={signal?:string;buyPressureRatio?:number};type C={tradeDate:string;candleTime:string;open:number;high:number;low:number;close:number;volume:number;boardSnapshot:unknown};type T={date:string;time:string;exitTime:string;outcome:string;pnl:number};
const avg=(x:number[])=>x.reduce((s,v)=>s+v,0)/x.length;const pct=(a:number,b:number)=>(a/b-1)*100;const board=(c:C):B|null=>typeof c.boardSnapshot==="string"?JSON.parse(c.boardSnapshot):c.boardSnapshot as B|null;
function clean(rows:C[]){const m=new Map<string,C[]>();for(const r of rows){const d=m.get(r.tradeDate)??[],p=d.at(-1);if(!p||!(r.low<p.close*.5||r.high>p.close*1.5))d.push(r);m.set(r.tradeDate,d)}return [...m.values()].filter(d=>d.length>100).slice(-40)}
function slp(d:C[],i:number){return pct(avg(d.slice(i-7,i+1).map(x=>x.close)),avg(d.slice(i-9,i-1).map(x=>x.close)))}
function exit(d:C[],i:number):Omit<T,"date"|"time">{const e=d[i].close,sl=e*1.006,tp=e*.985,cut=d[i].candleTime<="11:27"?"11:27":"15:25";for(let j=i+1;j<d.length&&d[j].candleTime<=cut;j++){if(d[j].high>=sl)return{exitTime:d[j].candleTime,outcome:"SL",pnl:(e-sl)*100};if(d[j].low<=tp)return{exitTime:d[j].candleTime,outcome:"TP",pnl:(e-tp)*100}}const last=[...d].reverse().find(x=>x.candleTime<=cut)!;return{exitTime:last.candleTime,outcome:"時間決済",pnl:(e-last.close)*100}}
function signal(d:C[],confirm:number,vol:number,maxDrop:number,boardMode:"sell"|"nonbuy"):T|null{const open=d[0].open;for(let i=20;i<d.length;i++){const c=d[i];if(c.candleTime<"09:35"||(c.candleTime>"11:00"&&c.candleTime<"12:50")||c.candleTime>"14:20")continue;const prior=d[i-1],level=Math.floor(prior.close/100)*100,vr=c.volume/avg(d.slice(i-20,i).map(x=>x.volume)),b=board(c);if(!(prior.close>=level&&c.close<level))continue;const j=i+confirm-1;if(j>=d.length||d[j].tradeDate!==c.tradeDate||d[j].candleTime>"15:25")continue;const entry=d[j];const held=d.slice(i,j+1).every(x=>x.close<level);const boardOk=boardMode==="sell"?b?.signal==="sell_pressure":b?.signal!=="buy_pressure";if(held&&pct(entry.close,open)>=maxDrop&&slp(d,j)<=-.02&&vr>=vol&&boardOk)return{date:entry.tradeDate,time:entry.candleTime,...exit(d,j)}}return null}
function stat(ts:T[]){const w=ts.filter(t=>t.pnl>0).length,p=ts.reduce((s,t)=>s+t.pnl,0),gp=ts.filter(t=>t.pnl>0).reduce((s,t)=>s+t.pnl,0),gl=-ts.filter(t=>t.pnl<0).reduce((s,t)=>s+t.pnl,0);return{n:ts.length,w,r:ts.length?w/ts.length*100:0,p,pf:gl?gp/gl:Infinity}}
async function main(){const db=await getDb();if(!db)throw Error("DB接続に失敗");const r=await db.execute(sql`SELECT tradeDate,candleTime,open,high,low,close,volume,boardSnapshot FROM rt_candles WHERE symbol='5803' ORDER BY tradeDate,candleTime`);const rows=(r as any)[0].map((x:any)=>({...x,tradeDate:String(x.tradeDate),candleTime:String(x.candleTime),open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume}))as C[];const ds=clean(rows),out:any[]=[];for(const confirm of [2,3,5])for(const vol of [.8,1,1.2])for(const maxDrop of [-1,-2,-3,-4])for(const mode of ["sell","nonbuy"]as const){const t=ds.map(d=>signal(d,confirm,vol,maxDrop,mode)).filter(Boolean)as T[];out.push({confirm,vol,maxDrop,mode,t,s:stat(t)})}out.sort((a,b)=>b.s.p-a.s.p||b.s.r-a.s.r);console.log(`フジクラ大台割れSHORT: ${ds[0][0].tradeDate}〜${ds.at(-1)![0].tradeDate}、40営業日、SL0.6%/TP1.5%、前場11:27強制決済`);for(const x of out.slice(0,15))console.log(`確認${x.confirm}本 vol${x.vol} 始値比${x.maxDrop}%以上 板${x.mode}: ${x.s.n}件 ${x.s.w}勝${x.s.n-x.s.w}敗 勝率${x.s.r.toFixed(1)}% ${x.s.p>=0?"+":""}${x.s.p.toFixed(0)}円 PF${x.s.pf.toFixed(2)} | 8/20 ${x.t.find((z:T)=>z.date==="2026-08-20")?.time??"-"}`);const best=out[0];console.log("--- 最上位明細 ---");best.t.forEach((t:T)=>console.log(`${t.date} ${t.time}->${t.exitTime} ${t.outcome} ${t.pnl>=0?"+":""}${t.pnl.toFixed(0)}円`));process.exit(0)}
main().catch(e=>{console.error(e);process.exit(1)});
