import { sql } from "drizzle-orm";
import { getDb } from "../server/db";

type Board = { signal?: string; buyPressureRatio?: number };
type Candle = { tradeDate: string; candleTime: string; open: number; high: number; low: number; close: number; volume: number; boardSnapshot: unknown };
type Trade = { date: string; time: string; side: "SHORT" | "LONG"; exitTime: string; outcome: string; pnl: number };
type Feature = { day: Candle[]; index: number; date: string; time: string; bpr: number; boardSignal: string; volumeRatio: number; slope: number; body: number; momentum: number; dayChange: number; amChange: number; bounce: number };
type S = { start: string; end: string; bpr: number; vol: number; slope: number; body: number; momentum: number; maxDrop: number; sl: number; tp: number };
type L = { start: string; end: string; bpr: number; vol: number; slope: number; bounce: number; amDrop: number; sl: number; tp: number };

const avg = (v: number[]) => v.reduce((s, x) => s + x, 0) / v.length;
const pct = (a: number, b: number) => (a / b - 1) * 100;
const board = (c: Candle): Board | null => typeof c.boardSnapshot === "string" ? JSON.parse(c.boardSnapshot) : c.boardSnapshot as Board | null;
const slope = (d: Candle[], i: number) => pct(avg(d.slice(i - 7, i + 1).map(x => x.close)), avg(d.slice(i - 9, i - 1).map(x => x.close)));
function days(rows: Candle[]) { const m = new Map<string, Candle[]>(); for (const r of rows) { const d = m.get(r.tradeDate) ?? [], p = d.at(-1); if (!p || !(r.low < p.close * .5 || r.high > p.close * 1.5)) d.push(r); m.set(r.tradeDate, d); } return [...m.values()].filter(d => d.length > 100).slice(-40); }
function exit(d: Candle[], i: number, side: Trade["side"], slPct: number, tpPct: number): Omit<Trade, "date" | "time" | "side"> { const e = d[i].close, sl = side === "LONG" ? e * (1 - slPct / 100) : e * (1 + slPct / 100), tp = side === "LONG" ? e * (1 + tpPct / 100) : e * (1 - tpPct / 100), cut = d[i].candleTime <= "11:27" ? "11:27" : "15:25"; for (let j = i + 1; j < d.length && d[j].candleTime <= cut; j++) { const c = d[j]; if (side === "LONG" ? c.low <= sl : c.high >= sl) return { exitTime: c.candleTime, outcome: "SL", pnl: (side === "LONG" ? sl - e : e - sl) * 100 }; if (side === "LONG" ? c.high >= tp : c.low <= tp) return { exitTime: c.candleTime, outcome: "TP", pnl: (side === "LONG" ? tp - e : e - tp) * 100 }; } const last = [...d].reverse().find(c => c.candleTime <= cut)!; return { exitTime: last.candleTime, outcome: "時間決済", pnl: (side === "LONG" ? last.close - e : e - last.close) * 100 }; }
function shortFeatures(d: Candle[]) { const a: Feature[] = [], open = d[0].open; for (let i = 20; i < d.length - 2; i++) { const c = d[i], p = d[i - 1], round = Math.floor(p.close / 100) * 100, j = i + 2; if (!(p.close >= round && c.close < round) || !d.slice(i, j + 1).every(x => x.close < round)) continue; const e = d[j], b = board(c); a.push({ day: d, index: j, date: e.tradeDate, time: c.candleTime, bpr: b?.buyPressureRatio ?? Infinity, boardSignal: b?.signal ?? "unknown", volumeRatio: c.volume / avg(d.slice(i - 20, i).map(x => x.volume)), slope: slope(d, j), body: pct(e.open, e.close), momentum: pct(e.close, d[Math.max(0, j - 3)].close), dayChange: pct(e.close, open), amChange: 0, bounce: 0 }); } return a; }
function longFeatures(d: Candle[]) { const a: Feature[] = [], open = d[0].open, am = d.filter(x => x.candleTime <= "11:27").at(-1)!; for (let i = 20; i < d.length; i++) { const c = d[i], b = board(c), low = Math.min(...d.slice(0, i + 1).map(x => x.low)), high10 = Math.max(...d.slice(i - 10, i).map(x => x.high)); if (!(c.high > high10 && c.close > c.open)) continue; a.push({ day: d, index: i, date: c.tradeDate, time: c.candleTime, bpr: b?.buyPressureRatio ?? 0, boardSignal: b?.signal ?? "unknown", volumeRatio: c.volume / avg(d.slice(i - 20, i).map(x => x.volume)), slope: slope(d, i), body: pct(c.open, c.close), momentum: 0, dayChange: 0, amChange: pct(am.close, open), bounce: pct(c.close, low) }); } return a; }
function pickS(fs: Feature[], p: S): Trade | null { const f = fs.find(x => x.time >= p.start && x.time <= p.end && x.boardSignal !== "buy_pressure" && x.bpr <= p.bpr && x.volumeRatio >= p.vol && x.slope <= p.slope && x.body >= p.body && x.momentum <= p.momentum && x.dayChange >= -p.maxDrop); return f ? { date: f.date, time: f.time, side: "SHORT", ...exit(f.day, f.index, "SHORT", p.sl, p.tp) } : null; }
function pickL(fs: Feature[], p: L): Trade | null { const f = fs.find(x => x.time >= p.start && x.time <= p.end && x.boardSignal !== "sell_pressure" && x.bpr <= p.bpr && x.volumeRatio >= p.vol && x.slope >= p.slope && x.bounce >= p.bounce && x.amChange <= -p.amDrop); return f ? { date: f.date, time: f.time, side: "LONG", ...exit(f.day, f.index, "LONG", p.sl, p.tp) } : null; }
function stats(ts: Trade[]) { const w = ts.filter(t => t.pnl > 0).length, p = ts.reduce((s, t) => s + t.pnl, 0), gp = ts.filter(t => t.pnl > 0).reduce((s, t) => s + t.pnl, 0), gl = -ts.filter(t => t.pnl < 0).reduce((s, t) => s + t.pnl, 0); return { n: ts.length, w, r: ts.length ? w / ts.length * 100 : 0, p, pf: gl ? gp / gl : Infinity }; }
function integrate(ts: Trade[]) { const days = Object.values(ts.reduce((m: Record<string, Trade[]>, x) => ((m[x.date] ??= []).push(x), m), {})); const out: Trade[] = []; for (const d of days) { let busy = "00:00"; for (const t of d.sort((a, b) => a.time.localeCompare(b.time))) if (t.time > busy) { out.push(t); busy = t.exitTime; } } return out; }
const fmt = (s: ReturnType<typeof stats>) => `${s.n}件 ${s.w}勝${s.n - s.w}敗 勝率${s.r.toFixed(1)}% ${s.p >= 0 ? "+" : ""}${s.p.toFixed(0)}円 PF${s.pf.toFixed(2)}`;
async function main() { const db = await getDb(); if (!db) throw Error("DB接続に失敗"); const res = await db.execute(sql`SELECT tradeDate,candleTime,open,high,low,close,volume,boardSnapshot FROM rt_candles WHERE symbol='5803' ORDER BY tradeDate,candleTime`); const d = days((res as any)[0].map((x: any) => ({ ...x, tradeDate: String(x.tradeDate), candleTime: String(x.candleTime), open: +x.open, high: +x.high, low: +x.low, close: +x.close, volume: +x.volume })) as Candle[]), sf = d.map(shortFeatures), lf = d.map(longFeatures), baselineP = 67318, target = baselineP * 1.2;
  const ss: { p: S; t: Trade[]; s: ReturnType<typeof stats> }[] = [], ls: { p: L; t: Trade[]; s: ReturnType<typeof stats> }[] = [];
  for (const start of ["09:45", "10:00"]) for (const end of ["10:30", "10:45", "11:00"]) for (const bpr of [.6, .7, .8, 1]) for (const vol of [1, 1.2, 1.5]) for (const slp of [-.02, -.05, -.1]) for (const body of [0, .05, .1]) for (const mom of [0, -.05, -.1]) for (const maxDrop of [2, 2.5, 3]) for (const sl of [.5, .6, .7]) for (const tp of [1.2, 1.5, 1.8]) { const p = { start, end, bpr, vol, slope: slp, body, momentum: mom, maxDrop, sl, tp }, t = sf.map(x => pickS(x, p)).filter(Boolean) as Trade[], s = stats(t); if (s.n >= 5 && s.r >= 65 && s.p > 0) ss.push({ p, t, s }); }
  for (const start of ["12:50", "13:00"]) for (const end of ["13:30", "14:00"]) for (const bpr of [.8, 1, 1.2, 1.5]) for (const vol of [.5, .7, 1]) for (const slp of [.02, .05, .1]) for (const bounce of [.8, 1, 1.2]) for (const amDrop of [.5, 1, 1.5]) for (const sl of [.3, .4, .5]) for (const tp of [.5, .6, .7, .8]) { if (tp <= sl) continue; const p = { start, end, bpr, vol, slope: slp, bounce, amDrop, sl, tp }, t = lf.map(x => pickL(x, p)).filter(Boolean) as Trade[], s = stats(t); if (s.n >= 4 && s.r >= 65 && s.p > 0) ls.push({ p, t, s }); }
  ss.sort((a,b) => b.s.r-a.s.r || b.s.p-a.s.p); ls.sort((a,b) => b.s.r-a.s.r || b.s.p-a.s.p); const finalists: any[] = [], frontier: any[] = []; for (const s of ss.slice(0, 100)) for (const l of ls.slice(0, 100)) { const t = integrate([...s.t, ...l.t]), z = stats(t), x = { s, l, t, z }; if (z.n >= 12) frontier.push(x); if (z.n >= 12 && z.r >= 80 && z.p >= target) finalists.push(x); } finalists.sort((a,b) => b.z.r-a.z.r || b.z.p-a.z.p);
  console.log(`フジクラ目標スイープ: 基準 A+B = ${fmt(stats(integrate([...sf.map(x=>pickS(x,{start:"09:45",end:"10:45",bpr:.8,vol:1.2,slope:-.02,body:0,momentum:0,maxDrop:3,sl:.6,tp:1.5})).filter(Boolean) as Trade[],...lf.map(x=>pickL(x,{start:"12:50",end:"14:00",bpr:1,vol:.7,slope:.02,bounce:.8,amDrop:1,sl:.5,tp:.5})).filter(Boolean) as Trade[]])))}; 損益目標 +${target.toFixed(0)}円。`);
  console.log(`SHORT候補 ${ss.length}件 / LONG候補 ${ls.length}件 / 目標達成の統合候補 ${finalists.length}件`);
  for (const x of finalists.slice(0, 10)) { const h = Math.ceil(d.length / 2), pivot = d[h - 1][0].tradeDate, first = stats(x.t.filter((t:Trade) => t.date <= pivot)), last = stats(x.t.filter((t:Trade) => t.date > pivot)); console.log(`\n統合 ${fmt(x.z)} | 前半 ${fmt(first)} | 後半 ${fmt(last)}`); console.log(`SHORT ${JSON.stringify(x.s.p)} => ${fmt(x.s.s)}`); console.log(`LONG ${JSON.stringify(x.l.p)} => ${fmt(x.l.s)}`); console.log(x.t.map((t:Trade)=>`${t.date} ${t.time} ${t.side} ${t.outcome} ${t.pnl>=0?"+":""}${t.pnl.toFixed(0)}`).join(" | ")); }
  const byWin = [...frontier].filter(x => x.z.r >= 80).sort((a,b) => b.z.p-a.z.p || b.z.r-a.z.r)[0], byProfit = [...frontier].filter(x => x.z.p >= target).sort((a,b) => b.z.r-a.z.r || b.z.p-a.z.p)[0]; for (const [label, x] of [["勝率80%以上で最大損益", byWin], ["損益目標以上で最大勝率", byProfit]] as const) { if (!x) { console.log(`\n${label}: 該当なし`); continue; } console.log(`\n${label}: ${fmt(x.z)}`); console.log(`SHORT ${JSON.stringify(x.s.p)} => ${fmt(x.s.s)}`); console.log(`LONG ${JSON.stringify(x.l.p)} => ${fmt(x.l.s)}`); console.log(x.t.map((t:Trade)=>`${t.date} ${t.time} ${t.side} ${t.outcome} ${t.pnl>=0?"+":""}${t.pnl.toFixed(0)}`).join(" | ")); }
  process.exit(0);
}
main().catch(e => { console.error(e); process.exit(1); });
