import { getDb } from "../server/db";
import { sql } from "drizzle-orm";

type Board = { buyPressureRatio?: number; signal?: string };
type C = { tradeDate: string; candleTime: string; open: number; high: number; low: number; close: number; volume: number; boardSnapshot?: unknown };
type Candidate = { source: "trendLong" | "trendShort" | "peakShort"; date: string; time: string; side: "long" | "short"; price: number; exitTime: string; pnl: number; outcome: string; gain: number; dropHigh: number; reboundLow: number; vol: number; bpr: number | null; boardSignal: string | null };

const mean = (v: number[]) => v.reduce((a,b)=>a+b,0)/v.length;
const pct = (a:number,b:number)=>(a/b-1)*100;
const slope = (d:C[], i:number) => pct(mean(d.slice(i-7,i+1).map(c=>c.close)), mean(d.slice(i-9,i-1).map(c=>c.close)));
const parseBoard = (c:C):Board|null => { const raw=c.boardSnapshot; if(!raw)return null; try{return typeof raw === "string" ? JSON.parse(raw) : raw as Board;}catch{return null;} };
function exit(d:C[], i:number, side:"long"|"short", sl:number,tp:number):Pick<Candidate,"exitTime"|"pnl"|"outcome"> { const e=d[i].close,slPx=side==="long"?e*(1-sl/100):e*(1+sl/100),tpPx=side==="long"?e*(1+tp/100):e*(1-tp/100); for(let j=i+1;j<d.length&&d[j].candleTime<="11:27";j++){const c=d[j],sh=side==="long"?c.low<=slPx:c.high>=slPx,th=side==="long"?c.high>=tpPx:c.low<=tpPx;if(sh)return{exitTime:c.candleTime,pnl:(side==="long"?slPx-e:e-slPx)*100,outcome:"SL"};if(th)return{exitTime:c.candleTime,pnl:(side==="long"?tpPx-e:e-tpPx)*100,outcome:"TP"};}const last=[...d].reverse().find(c=>c.candleTime<="11:27")!;return{exitTime:last.candleTime,pnl:(side==="long"?last.close-e:e-last.close)*100,outcome:"時間決済"}; }
function make(d:C[],i:number,source:Candidate["source"],side:"long"|"short",sl:number,tp:number):Candidate { const c=d[i], sofar=d.slice(0,i+1), board=parseBoard(c), e=exit(d,i,side,sl,tp); return {source,date:c.tradeDate,time:c.candleTime,side,price:c.close,...e,gain:pct(c.close,d[0].open),dropHigh:-pct(c.close,Math.max(...sofar.map(x=>x.high))),reboundLow:pct(c.close,Math.min(...sofar.map(x=>x.low))),vol:c.volume/mean(d.slice(i-20,i).map(x=>x.volume)),bpr:typeof board?.buyPressureRatio==="number"?board.buyPressureRatio:null,boardSignal:board?.signal??null}; }
function candidates(day:C[]):Candidate[]{ const out:Candidate[]=[];let high=-Infinity;for(let i=20;i<day.length;i++){const c=day[i];high=Math.max(high,c.high);if(c.candleTime<"10:00"||c.candleTime>"11:27")continue;const gain=pct(c.close,day[0].open),drop=-gain,vol=c.volume/mean(day.slice(i-20,i).map(x=>x.volume));if(gain>=1.5&&gain<=2.5&&slope(day,i)>=.02&&c.close>Math.max(...day.slice(i-20,i).map(x=>x.high))&&c.close>c.open&&vol>=1) {out.push(make(day,i,"trendLong","long",.8,1));break;}} for(let i=20;i<day.length;i++){const c=day[i];if(c.candleTime<"10:00"||c.candleTime>"11:27")continue;const drop=-pct(c.close,day[0].open),vol=c.volume/mean(day.slice(i-20,i).map(x=>x.volume));if(drop>=.5&&drop<=4&&slope(day,i)<=-.02&&c.close<Math.min(...day.slice(i-5,i).map(x=>x.low))&&c.close<c.open&&vol>=1.2){out.push(make(day,i,"trendShort","short",.8,1.5));break;}} high=-Infinity;for(let i=20;i<day.length;i++){const c=day[i];high=Math.max(high,c.high);if(c.candleTime<"09:45"||c.candleTime>"11:27")continue;const vol=c.volume/mean(day.slice(i-20,i).map(x=>x.volume));if(pct(high,day[0].open)>=2.5&&pct(high,c.close)>=.4&&-pct(c.close,c.open)>=.1&&vol>=1&&Math.max(...day.slice(Math.max(0,i-2),i+1).map(x=>x.high))===high){out.push(make(day,i,"peakShort","short",.8,1.5));break;}}return out; }
function reentryCandidates(day:C[], cooldown:number):Candidate[]{const out:Candidate[]=[];let high=-Infinity,lastLong=-999,lastTrendShort=-999,lastPeak=-999;for(let i=20;i<day.length;i++){const c=day[i];high=Math.max(high,c.high);if(c.candleTime<"10:00"||c.candleTime>"11:27")continue;const gain=pct(c.close,day[0].open),drop=-gain,vol=c.volume/mean(day.slice(i-20,i).map(x=>x.volume));if(i-lastLong>=cooldown&&gain>=1.5&&gain<=2.5&&slope(day,i)>=.02&&c.close>Math.max(...day.slice(i-20,i).map(x=>x.high))&&c.close>c.open&&vol>=1){out.push(make(day,i,"trendLong","long",.7,1));lastLong=i;}if(i-lastTrendShort>=cooldown&&drop>=.5&&drop<=4&&slope(day,i)<=-.02&&c.close<Math.min(...day.slice(i-5,i).map(x=>x.low))&&c.close<c.open&&vol>=1.2){out.push(make(day,i,"trendShort","short",.6,1.8));lastTrendShort=i;}if(i-lastPeak>=cooldown&&pct(high,day[0].open)>=2.5&&pct(high,c.close)>=.4&&-pct(c.close,c.open)>=.1&&vol>=1&&Math.max(...day.slice(Math.max(0,i-2),i+1).map(x=>x.high))===high){out.push(make(day,i,"peakShort","short",.6,1.8));lastPeak=i;}}return out;}
function integrate(c:Candidate[]){const a:Candidate[]=[];for(const items of Object.values(c.reduce((m:Record<string,Candidate[]>,x)=>((m[x.date]??=[]).push(x),m),{}))){let busy="00:00";for(const x of items.sort((p,q)=>p.time.localeCompare(q.time)||p.side.localeCompare(q.side))){if(x.time>busy){a.push(x);busy=x.exitTime;}}}return a;}
function stat(t:Candidate[]){const w=t.filter(x=>x.pnl>0),l=t.filter(x=>x.pnl<0),p=t.reduce((s,x)=>s+x.pnl,0);return{n:t.length,w:w.length,rate:t.length?w.length/t.length*100:0,pnl:p,pf:l.length?w.reduce((s,x)=>s+x.pnl,0)/-l.reduce((s,x)=>s+x.pnl,0):Infinity};}
function sanitize(rows:C[]){const m=new Map<string,C[]>();for(const r of rows)(m.get(r.tradeDate)??m.set(r.tradeDate,[]).get(r.tradeDate)!).push(r);for(const[d,a]of m){const b:C[]=[];for(const c of a){const p=b.at(-1);if(p&&(c.low<p.close*.5||c.high>p.close*1.5))continue;b.push(c)}m.set(d,b)}return m;}
async function main(){const db=await getDb();if(!db)throw Error("DB接続失敗");const rows=((await db.execute(sql`SELECT tradeDate,candleTime,open,high,low,close,volume,boardSnapshot FROM rt_candles WHERE symbol='8035' ORDER BY tradeDate,candleTime`))as any)[0].map((x:any)=>({...x,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume}))as C[];const days=[...sanitize(rows).values()].filter(d=>d.length>50).slice(-40);const base=integrate(days.flatMap(candidates));const bs=stat(base);console.log(`BASE ${bs.n}件 ${bs.w}勝${bs.n-bs.w}敗 勝率${bs.rate.toFixed(1)}% ${bs.pnl.toFixed(0)}円 PF${bs.pf.toFixed(2)} targetPnl=${(bs.pnl*1.2).toFixed(0)}`);
const all=days.flatMap(candidates);const results:any[]=[];for(const longEnd of ["10:45","11:00","11:27"])for(const shortEnd of ["10:45","11:00","11:27"])for(const minVol of [1,1.1,1.2])for(const bprMax of [1.2,1.4,1.6,99])for(const allowNeutral of [true,false]){const filtered=all.filter(x=>{if(x.side==="long"){if(x.time>longEnd||x.vol<minVol)return false;if(x.boardSignal==="sell_pressure")return false;return x.bpr===null||x.bpr<=bprMax;}if(x.time>shortEnd||x.vol<minVol)return false;if(x.boardSignal==="buy_pressure")return false;if(!allowNeutral&&x.boardSignal==="neutral")return false;return x.bpr===null||x.bpr<=bprMax;});const s=stat(integrate(filtered));if(s.n>=12)results.push({longEnd,shortEnd,minVol,bprMax,allowNeutral,...s,tr:integrate(filtered)});}
	for(const cooldown of [5,10,15]){const r=integrate(days.flatMap(d=>reentryCandidates(d,cooldown)).filter(x=>x.vol>=1&&x.bpr!==null&&x.bpr<=1.6&&(x.side==="long"?x.boardSignal!=="sell_pressure":x.time<="11:00"&&x.boardSignal!=="buy_pressure")));const s=stat(r);console.log(`REENTRY cooldown${cooldown}: ${s.n}件 ${s.w}勝${s.n-s.w}敗 ${s.rate.toFixed(1)}% ${s.pnl.toFixed(0)}円 PF${s.pf.toFixed(2)}`);}
const goal=results.filter(x=>x.rate>=75&&x.pnl>=bs.pnl*1.2).sort((a,b)=>b.pnl-a.pnl||b.rate-a.rate);console.log(`GOAL達成候補 ${goal.length}件`);(goal.length?goal:results.sort((a,b)=>(b.rate*0.65+b.pnl/bs.pnl*35)-(a.rate*0.65+a.pnl/bs.pnl*35))).slice(0,12).forEach(x=>console.log(`longEnd${x.longEnd} shortEnd${x.shortEnd} vol${x.minVol} bpr<=${x.bprMax} neutral=${x.allowNeutral}: ${x.n}件 ${x.w}勝${x.n-x.w}敗 ${x.rate.toFixed(1)}% ${x.pnl.toFixed(0)}円 PF${x.pf.toFixed(2)}`));
 const precision=results.find(x=>x.longEnd==="11:27"&&x.shortEnd==="11:00"&&x.minVol===1&&x.bprMax===1.6&&x.allowNeutral===true);if(precision){const p=precision.tr as Candidate[],first=stat(p.filter(x=>x.date<="2026-07-21")),second=stat(p.filter(x=>x.date>="2026-07-22"));console.log(`PRECISION時系列 前半${first.n}件 ${first.w}勝${first.n-first.w}敗 ${first.rate.toFixed(1)}% ${first.pnl.toFixed(0)}円 / 後半${second.n}件 ${second.w}勝${second.n-second.w}敗 ${second.rate.toFixed(1)}% ${second.pnl.toFixed(0)}円`);}
	const byDate=new Map(days.map(d=>[d[0].tradeDate,d]));
	const baseFilter=(x:Candidate)=>x.vol>=1&&x.bpr!==null&&x.bpr<=1.6&&(x.side==="long"?x.time<="11:27"&&x.boardSignal!=="sell_pressure":x.time<="11:00"&&x.boardSignal!=="buy_pressure");
	const riskRows:any[]=[];
	for(const lsl of [.6,.7,.8])for(const ltp of [.8,1,1.2,1.5])for(const ssl of [.6,.7,.8])for(const stp of [1.2,1.5,1.8,2]){if(ltp<=lsl||stp<=ssl)continue;const repriced=all.map(x=>{const day=byDate.get(x.date)!;const i=day.findIndex(c=>c.candleTime===x.time);const e=exit(day,i,x.side,x.side==="long"?lsl:ssl,x.side==="long"?ltp:stp);return{...x,...e}}).filter(baseFilter);const s=stat(integrate(repriced));if(s.n>=12)riskRows.push({lsl,ltp,ssl,stp,...s,tr:integrate(repriced)});}
	const riskGoal=riskRows.filter(x=>x.rate>=75&&x.pnl>=bs.pnl*1.2).sort((a,b)=>b.pnl-a.pnl||b.rate-a.rate);console.log(`RISK再最適化 目標達成候補 ${riskGoal.length}件`);(riskGoal.length?riskGoal:riskRows.sort((a,b)=>(b.rate*0.65+b.pnl/bs.pnl*35)-(a.rate*0.65+a.pnl/bs.pnl*35))).slice(0,10).forEach(x=>console.log(`L${x.lsl}/${x.ltp} S${x.ssl}/${x.stp}: ${x.n}件 ${x.w}勝${x.n-x.w}敗 ${x.rate.toFixed(1)}% ${x.pnl.toFixed(0)}円 PF${x.pf.toFixed(2)}`));
if(goal[0]){const x=goal[0],a=x.tr as Candidate[],e=stat(a.filter(t=>t.date<="2026-07-21")),l=stat(a.filter(t=>t.date>="2026-07-22"));console.log(`BEST時系列 前半${e.n}件 ${e.rate.toFixed(1)}% ${e.pnl.toFixed(0)}円 / 後半${l.n}件 ${l.rate.toFixed(1)}% ${l.pnl.toFixed(0)}円`);a.forEach(t=>console.log(`BEST ${t.date} ${t.time} ${t.source} ${t.side} ${t.outcome} ${t.pnl.toFixed(0)} bpr=${t.bpr?.toFixed(2)??"NA"} ${t.boardSignal??"NA"}`));}process.exit(0)}main().catch(e=>{console.error(e);process.exit(1)});
